In [ ]:
#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: 
APP_SECRET: 

#계좌번호 앞 8자리
CANO: 
#계좌번호 뒤 2자리
ACNT_PRDT_CD: 

#실전투자
URL_BASE: 
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL:

In [ ]:
# 야물 파일 로딩
import requests
import json
import datetime
import time
import yaml

with open('config.yaml', encoding='UTF-8') as f:
    _cfg = yaml.load(f, Loader=yaml.FullLoader)
APP_KEY = _cfg['APP_KEY']
APP_SECRET = _cfg['APP_SECRET']
ACCESS_TOKEN = ""
CANO = _cfg['CANO']
ACNT_PRDT_CD = _cfg['ACNT_PRDT_CD']
DISCORD_WEBHOOK_URL = _cfg['DISCORD_WEBHOOK_URL']
URL_BASE = _cfg['URL_BASE']

In [ ]:
# sapmle code
import requests
import json
import datetime
import time
import yaml

with open('config.yaml', encoding='UTF-8') as f:
    _cfg = yaml.load(f, Loader=yaml.FullLoader)
APP_KEY = _cfg['APP_KEY']
APP_SECRET = _cfg['APP_SECRET']
ACCESS_TOKEN = ""
CANO = _cfg['CANO']
ACNT_PRDT_CD = _cfg['ACNT_PRDT_CD']
DISCORD_WEBHOOK_URL = _cfg['DISCORD_WEBHOOK_URL']
URL_BASE = _cfg['URL_BASE']

def send_message(msg):
    """디스코드 메세지 전송"""
    now = datetime.now()
    message = {"content": f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] {str(msg)}"}
    requests.post(DISCORD_WEBHOOK_URL, data=message)
    print(message)

def get_access_token():
    """토큰 발급"""
    headers = {"content-type":"application/json"}
    body = {"grant_type":"client_credentials",
    "appkey":APP_KEY, 
    "appsecret":APP_SECRET}
    PATH = "oauth2/tokenP"
    URL = f"{URL_BASE}/{PATH}"
    res = requests.post(URL, headers=headers, data=json.dumps(body))
    ACCESS_TOKEN = res.json()["access_token"]
    return ACCESS_TOKEN
    
def hashkey(datas):
    """암호화"""
    PATH = "uapi/hashkey"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
    'content-Type' : 'application/json',
    'appKey' : APP_KEY,
    'appSecret' : APP_SECRET,
    }
    res = requests.post(URL, headers=headers, data=json.dumps(datas))
    hashkey = res.json()["HASH"]
    return hashkey

def get_current_price(code="005930"):
    """현재가 조회"""
    PATH = "uapi/domestic-stock/v1/quotations/inquire-price"
    URL = f"{URL_BASE}/{PATH}"
    headers = {"Content-Type":"application/json", 
            "authorization": f"Bearer {ACCESS_TOKEN}",
            "appKey":APP_KEY,
            "appSecret":APP_SECRET,
            "tr_id":"FHKST01010100"}
    params = {
    "fid_cond_mrkt_div_code":"J",
    "fid_input_iscd":code,
    }
    res = requests.get(URL, headers=headers, params=params)
    return int(res.json()['output']['stck_prpr'])

def get_target_price(code="005930"):
    """변동성 돌파 전략으로 매수 목표가 조회"""
    PATH = "uapi/domestic-stock/v1/quotations/inquire-daily-price"
    URL = f"{URL_BASE}/{PATH}"
    headers = {"Content-Type":"application/json", 
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"FHKST01010400"}
    params = {
    "fid_cond_mrkt_div_code":"J",
    "fid_input_iscd":code,
    "fid_org_adj_prc":"1",
    "fid_period_div_code":"D"
    }
    res = requests.get(URL, headers=headers, params=params)
    stck_oprc = int(res.json()['output'][0]['stck_oprc']) #오늘 시가
    stck_hgpr = int(res.json()['output'][1]['stck_hgpr']) #전일 고가
    stck_lwpr = int(res.json()['output'][1]['stck_lwpr']) #전일 저가
    target_price = stck_oprc + (stck_hgpr - stck_lwpr) * 0.5
    return target_price

def get_stock_balance():
    """주식 잔고조회"""
    PATH = "uapi/domestic-stock/v1/trading/inquire-balance"
    URL = f"{URL_BASE}/{PATH}"
    headers = {"Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC8434R",
        "custtype":"P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "",
        "INQR_DVSN": "02",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": "",
        "CTX_AREA_NK100": ""
    }
    res = requests.get(URL, headers=headers, params=params)
    stock_list = res.json()['output1']
    evaluation = res.json()['output2']
    stock_dict = {}
    send_message(f"====주식 보유잔고====")
    for stock in stock_list:
        if int(stock['hldg_qty']) > 0:
            stock_dict[stock['pdno']] = stock['hldg_qty']
            send_message(f"{stock['prdt_name']}({stock['pdno']}): {stock['hldg_qty']}주")
            time.sleep(0.1)
    send_message(f"주식 평가 금액: {evaluation[0]['scts_evlu_amt']}원")
    time.sleep(0.1)
    send_message(f"평가 손익 합계: {evaluation[0]['evlu_pfls_smtl_amt']}원")
    time.sleep(0.1)
    send_message(f"총 평가 금액: {evaluation[0]['tot_evlu_amt']}원")
    time.sleep(0.1)
    send_message(f"=================")
    return stock_dict

def get_balance():
    """현금 잔고조회"""
    PATH = "uapi/domestic-stock/v1/trading/inquire-psbl-order"
    URL = f"{URL_BASE}/{PATH}"
    headers = {"Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC8908R",
        "custtype":"P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": "005930",
        "ORD_UNPR": "65500",
        "ORD_DVSN": "01",
        "CMA_EVLU_AMT_ICLD_YN": "Y",
        "OVRS_ICLD_YN": "Y"
    }
    res = requests.get(URL, headers=headers, params=params)
    cash = res.json()['output']['ord_psbl_cash']
    send_message(f"주문 가능 현금 잔고: {cash}원")
    return int(cash)

def buy(code="005930", qty="1"):
    """주식 시장가 매수"""  
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": str(int(qty)),
        "ORD_UNPR": "0",
    }
    headers = {"Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0802U",
        "custtype":"P",
        "hashkey" : hashkey(data)
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    if res.json()['rt_cd'] == '0':
        send_message(f"[매수 성공]{str(res.json())}")
        return True
    else:
        send_message(f"[매수 실패]{str(res.json())}")
        return False

def sell(code="005930", qty="1"):
    """주식 시장가 매도"""
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": qty,
        "ORD_UNPR": "0",
    }
    headers = {"Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0801U",
        "custtype":"P",
        "hashkey" : hashkey(data)
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    if res.json()['rt_cd'] == '0':
        send_message(f"[매도 성공]{str(res.json())}")
        return True
    else:
        send_message(f"[매도 실패]{str(res.json())}")
        return False


# 자동매매 시작
try:
    ACCESS_TOKEN = get_access_token()

    symbol_list = ["005930","035720","000660","069500"] # 매수 희망 종목 리스트
    bought_list = [] # 매수 완료된 종목 리스트
    total_cash = get_balance() # 보유 현금 조회
    stock_dict = get_stock_balance() # 보유 주식 조회
    for sym in stock_dict.keys():
        bought_list.append(sym)
    target_buy_count = 3 # 매수할 종목 수
    buy_percent = 0.33 # 종목당 매수 금액 비율
    buy_amount = total_cash * buy_percent  # 종목별 주문 금액 계산
    soldout = False

    send_message("===국내 주식 자동매매 프로그램을 시작합니다===")
    while True:
        t_now = datetime.now()
        t_9 = t_now.replace(hour=9, minute=0, second=0, microsecond=0)
        t_start = t_now.replace(hour=9, minute=5, second=0, microsecond=0)
        t_sell = t_now.replace(hour=15, minute=15, second=0, microsecond=0)
        t_exit = t_now.replace(hour=15, minute=20, second=0,microsecond=0)
        today = datetime.today().weekday()
        if today == 5 or today == 6:  # 토요일이나 일요일이면 자동 종료
            send_message("주말이므로 프로그램을 종료합니다.")
            break
        if t_9 < t_now < t_start and soldout == False: # 잔여 수량 매도
            for sym, qty in stock_dict.items():
                sell(sym, qty)
            soldout == True
            bought_list = []
            stock_dict = get_stock_balance()
        if t_start < t_now < t_sell :  # AM 09:05 ~ PM 03:15 : 매수
            for sym in symbol_list:
                if len(bought_list) < target_buy_count:
                    if sym in bought_list:
                        continue
                    target_price = get_target_price(sym)
                    current_price = get_current_price(sym)
                    if target_price < current_price:
                        buy_qty = 0  # 매수할 수량 초기화
                        buy_qty = int(buy_amount // current_price)
                        if buy_qty > 0:
                            send_message(f"{sym} 목표가 달성({target_price} < {current_price}) 매수를 시도합니다.")
                            result = buy(sym, buy_qty)
                            if result:
                                soldout = False
                                bought_list.append(sym)
                                get_stock_balance()
                    time.sleep(1)
            time.sleep(1)
            if t_now.minute == 30 and t_now.second <= 5: 
                get_stock_balance()
                time.sleep(5)
        if t_sell < t_now < t_exit:  # PM 03:15 ~ PM 03:20 : 일괄 매도
            if soldout == False:
                stock_dict = get_stock_balance()
                for sym, qty in stock_dict.items():
                    sell(sym, qty)
                soldout = True
                bought_list = []
                time.sleep(1)
        if t_exit < t_now:  # PM 03:20 ~ :프로그램 종료
            send_message("프로그램을 종료합니다.")
            break
except Exception as e:
    send_message(f"[오류 발생]{e}")
    time.sleep(1)

# 코드리뷰 및 연습

In [ ]:
# 디스코드에 메시지 전송
from datetime import datetime
import requests


DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1433043872300273694/hJS03AOUeVijblWt_5jFP93H5-k3PFzFXo97OiuRJCFz7i54Xyx4qc97rO6eSBf3t-lo"

def send_message(msg):
    """디스코드 메세지 전송"""
    now = datetime.now()
    message = {"content": f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] {str(msg)}"}
    requests.post(DISCORD_WEBHOOK_URL, data=message)
    print(message)
    
send_message(f"====testing====")

{'content': '[2025-11-07 13:27:05] ====testing===='}

In [ ]:
def hashkey(datas):
    """암호화"""
    PATH = "uapi/hashkey"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
    'content-Type' : 'application/json',
    'appKey' : APP_KEY,
    'appSecret' : APP_SECRET,
    }
    res = requests.post(URL, headers=headers, data=json.dumps(datas))
    print(res.json())
    hashkey = res.json()["HASH"]
    return hashkey

code = "005930"

data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": str(1),
        "ORD_UNPR": "0",
    }

hashkey(data)

{'BODY': {'CANO': '43424620', 'ACNT_PRDT_CD': '01', 'PDNO': '005930', 'ORD_DVSN': '01', 'ORD_QTY': '1', 'ORD_UNPR': '0'}, 'HASH': '6387e0859f7dc2dfcea911efcd75bf059be4685269ab333d2525fde7efa1d332'}

'6387e0859f7dc2dfcea911efcd75bf059be4685269ab333d2525fde7efa1d332'

In [ ]:
# 엑세스 토큰 생성
import json
import os
from datetime import datetime
import yaml

# 토큰 파일 경로 설정
config_root = os.path.join(os.path.expanduser("~"), "workspace", "mini_project")
token_tmp = os.path.join(
    config_root, f"KIS{datetime.today().strftime('%Y%m%d')}"
)  # 토큰 로컬저장시 파일명 년월일

# 접근토큰 관리하는 파일 존재여부 체크, 없으면 생성
if not os.path.exists(token_tmp):
    f = open(token_tmp, "w+")
    f.close()  # 파일 닫기 추가 (권장)


def save_token(my_token, my_expired):
    """토큰 저장"""
    valid_date = datetime.strptime(my_expired, "%Y-%m-%d %H:%M:%S")
    with open(token_tmp, "w", encoding="utf-8") as f:
        f.write(f"token: {my_token}\n")
        f.write(f"valid-date: {valid_date}\n")
    send_message(f"token stored in {token_tmp}")


def read_token():
    """저장된 토큰 불러오기 (만료 여부 확인)"""
    try:
        # 토큰이 저장된 파일 읽기
        with open(token_tmp, encoding="UTF-8") as f:
            tkg_tmp = yaml.load(f, Loader=yaml.FullLoader)

        # 토큰 만료 일,시간
        exp_dt = datetime.strftime(tkg_tmp["valid-date"], "%Y-%m-%d %H:%M:%S")
        # 현재일자,시간
        now_dt = datetime.today().strftime("%Y-%m-%d %H:%M:%S")

        # 저장된 토큰 만료일자 체크 (만료일시 > 현재일시 인경우 보관 토큰 리턴)
        if exp_dt > now_dt:
            return tkg_tmp["token"]
        else:
            send_message(f"token expired")
            return None
    except Exception:
        return None


def get_access_token():
    """토큰 발급 (저장된 토큰이 있으면 재사용, 없거나 만료되었으면 새로 발급)"""
    
    # 기존 발급된 토큰이 있는지 확인
    saved_token = read_token()
    
    if saved_token is None:  # 기존 발급 토큰 확인이 안되면 발급처리
        headers = {"content-type":"application/json"}
        body = {"grant_type":"client_credentials",
        "appkey":APP_KEY, 
        "appsecret":APP_SECRET}
        PATH = "oauth2/tokenP"
        URL = f"{URL_BASE}/{PATH}"
        res = requests.post(URL, headers=headers, data=json.dumps(body))
        
        if res.status_code == 200:
            ACCESS_TOKEN = res.json()["access_token"]
            # 토큰 만료일시 가져오기
            my_expired = res.json()["access_token_token_expired"]
            # 새로 발급 받은 토큰 저장
            save_token(ACCESS_TOKEN, my_expired)
            
            return ACCESS_TOKEN
        else:
            print("토큰 발급 실패!")
            return None
    else:
        # 기존 발급 토큰 확인되어 기존 토큰 사용
        send_message(f"saved token loading")
        return saved_token

token = get_access_token()
print(token)

{'content': '[2025-11-07 13:28:40] ====saved token loading===='}
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjAyOWFjYTA1LTI1ZTItNDJkOC04YTM2LWFjYWI0MWNiM2FiNyIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc2MjU3NTk2MiwiaWF0IjoxNzYyNDg5NTYyLCJqdGkiOiJQU1M3WkY5QUVBbVA1QWJtSnVOeWs4WTdBd3RmbnhmNmk5ZTYifQ.rl_P1z5rTEf2so_I3vImGfopmFWemuxIi7XjQQeDrcYLZYX9iy7LxIZWBfAB06cB9YSiF_2sGu_wt4o5trDmqA

In [ ]:
with open(token_tmp, encoding="UTF-8") as f:
    tkg_tmp = yaml.load(f, Loader=yaml.FullLoader)

# 토큰 만료 일,시간
exp_dt = datetime.strftime(tkg_tmp["valid-date"], "%Y-%m-%d %H:%M:%S")
        
print(exp_dt)

2025-11-08 13:26:02

In [ ]:
# 토큰 파일 경로 설정
from datetime import datetime
import os
import yaml

config_root = os.path.join(os.path.expanduser("~"), "workspace", "mini_project")
token_tmp = os.path.join(
    config_root, f"KIS{datetime.today().strftime('%Y%m%d')}"
)  # 토큰 로컬저장시 파일명 년월일

# 접근토큰 관리하는 파일 존재여부 체크, 없으면 생성
if os.path.exists(token_tmp) == False:
    f = open(token_tmp, "w+")
    f.close()  # 파일 닫기 추가 (권장)


# 토큰 발급 받아 저장 (토큰값, 토큰 유효시간,1일, 6시간 이내 발급신청시는 기존 토큰값과 동일, 발급시 알림톡 발송)
def save_token(my_token, my_expired):
    valid_date = datetime.strptime(my_expired, "%Y-%m-%d %H:%M:%S")
    with open(token_tmp, "w", encoding="utf-8") as f:
        f.write(f"token: {my_token}\n")
        f.write(f"valid-date: {valid_date}\n")


# 토큰 확인 (토큰값, 토큰 유효시간_1일, 6시간 이내 발급신청시는 기존 토큰값과 동일, 발급시 알림톡 발송)
def read_token():
    try:
        # 토큰이 저장된 파일 읽기
        with open(token_tmp, encoding="UTF-8") as f:
            tkg_tmp = yaml.load(f, Loader=yaml.FullLoader)

        # 토큰 만료 일,시간
        exp_dt = datetime.strftime(tkg_tmp["valid-date"], "%Y-%m-%d %H:%M:%S")
        # 현재일자,시간
        now_dt = datetime.today().strftime("%Y-%m-%d %H:%M:%S")

        # 저장된 토큰 만료일자 체크 (만료일시 > 현재일시 인경우 보관 토큰 리턴)
        if exp_dt > now_dt:
            return tkg_tmp["token"]
        else:
            return None
    except Exception:
        return None

In [ ]:
import shutil

# 오늘날짜 이전에 발급된 토큰을 expired 디렉토리로 옮기는 함수
def move_old_tokens_to_expired():
    """오늘 날짜 이전에 발급된 토큰 파일들을 expired 디렉토리로 이동합니다."""
    try:
        expired_dir = os.path.join(config_root, "expired")
        if not os.path.exists(expired_dir):
            os.makedirs(expired_dir)

        today = datetime.today().date()
        # config_root 하위의 모든 토큰 파일을 순회
        for fname in os.listdir(config_root):
            if fname.startswith("KIS") and fname[3:11].isdigit():
                token_date_str = fname[3:11]
                try:
                    token_date = datetime.strptime(token_date_str, "%Y%m%d").date()
                except Exception:
                    continue  # 파일명이 날짜 형식에 맞지 않으면 스킵

                if token_date < today:
                    token_file_path = os.path.join(config_root, fname)
                    # 파일명에 타임스탬프 추가하여 이동 (중복 방지)
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    expired_file_path = os.path.join(expired_dir, f"{timestamp}_{fname}")
                    try:
                        shutil.move(token_file_path, expired_file_path)
                        send_message(f"오늘 이전({token_date})에 발급된 토큰 파일을 {expired_file_path}로 이동했습니다.")
                    except Exception as e:
                        send_message(f"{fname} 파일 이동 중 오류: {str(e)}")
    except Exception as e:
        send_message(f"만료된 토큰 파일 이동 작업 전체에서 오류 발생: {str(e)}")
    
move_old_tokens_to_expired()

{'content': '[2025-11-11 17:08:03] 오늘 이전(2025-11-08)에 발급된 토큰 파일을 /home/mycom/workspace/mini_project/expired/20251111_170803_KIS20251108로 이동했습니다.'}
{'content': '[2025-11-11 17:08:04] 오늘 이전(2025-11-10)에 발급된 토큰 파일을 /home/mycom/workspace/mini_project/expired/20251111_170804_KIS20251110로 이동했습니다.'}

# 공식 github 에 나와있는 kis_auth.py

In [ ]:
# -*- coding: utf-8 -*-
# ====|  (REST) 접근 토큰 / (Websocket) 웹소켓 접속키 발급 에 필요한 API 호출 샘플 아래 참고하시기 바랍니다.  |=====================
# ====|  API 호출 공통 함수 포함                                  |=====================

import asyncio
import copy
import json
import logging
import os
import time
from base64 import b64decode
from collections import namedtuple
from collections.abc import Callable
from datetime import datetime
from io import StringIO

import pandas as pd

# pip install requests (패키지설치)
import requests

# 웹 소켓 모듈을 선언한다.
import websockets

# pip install PyYAML (패키지설치)
import yaml
from Crypto.Cipher import AES

# pip install pycryptodome
from Crypto.Util.Padding import unpad

clearConsole = lambda: os.system("cls" if os.name in ("nt", "dos") else "clear")

key_bytes = 32
config_root = os.path.join(os.path.expanduser("~"), "workspace", "mini_project")
# config_root = "$HOME/KIS/config/"  # 토큰 파일이 저장될 폴더, 제3자가 찾기 어렵도록 경로 설정하시기 바랍니다.
# token_tmp = config_root + 'KIS000000'  # 토큰 로컬저장시 파일 이름 지정, 파일이름을 토큰값이 유추가능한 파일명은 삼가바랍니다.
# token_tmp = config_root + 'KIS' + datetime.today().strftime("%Y%m%d%H%M%S")  # 토큰 로컬저장시 파일명 년월일시분초
token_tmp = os.path.join(
    config_root, f"KIS{datetime.today().strftime('%Y%m%d')}")  # 토큰 로컬저장시 파일명 년월일

# 접근토큰 관리하는 파일 존재여부 체크, 없으면 생성
if os.path.exists(token_tmp) == False:
    f = open(token_tmp, "w+")

# 앱키, 앱시크리트, 토큰, 계좌번호 등 저장관리, 자신만의 경로와 파일명으로 설정하시기 바랍니다.
# pip install PyYAML (패키지설치)
with open(os.path.join(config_root, "kis_devlp.yaml"), encoding="UTF-8") as f:
    _cfg = yaml.load(f, Loader=yaml.FullLoader)

_TRENV = tuple()
_last_auth_time = datetime.now()
_autoReAuth = False
_DEBUG = False
_isPaper = False
_smartSleep = 0.1

# 기본 헤더값 정의
_base_headers = {
    "Content-Type": "application/json",
    "Accept": "text/plain",
    "charset": "UTF-8",
    "User-Agent": _cfg["my_agent"],
}


# 토큰 발급 받아 저장 (토큰값, 토큰 유효시간,1일, 6시간 이내 발급신청시는 기존 토큰값과 동일, 발급시 알림톡 발송)
def save_token(my_token, my_expired):
    # print(type(my_expired), my_expired)
    valid_date = datetime.strptime(my_expired, "%Y-%m-%d %H:%M:%S")
    # print('Save token date: ', valid_date)
    with open(token_tmp, "w", encoding="utf-8") as f:
        f.write(f"token: {my_token}\n")
        f.write(f"valid-date: {valid_date}\n")


# 토큰 확인 (토큰값, 토큰 유효시간_1일, 6시간 이내 발급신청시는 기존 토큰값과 동일, 발급시 알림톡 발송)
def read_token():
    try:
        # 토큰이 저장된 파일 읽기
        with open(token_tmp, encoding="UTF-8") as f:
            tkg_tmp = yaml.load(f, Loader=yaml.FullLoader)

        # 토큰 만료 일,시간
        exp_dt = datetime.strftime(tkg_tmp["valid-date"], "%Y-%m-%d %H:%M:%S")
        # 현재일자,시간
        now_dt = datetime.today().strftime("%Y-%m-%d %H:%M:%S")

        # print('expire dt: ', exp_dt, ' vs now dt:', now_dt)
        # 저장된 토큰 만료일자 체크 (만료일시 > 현재일시 인경우 보관 토큰 리턴)
        if exp_dt > now_dt:
            return tkg_tmp["token"]
        else:
            # print('Need new token: ', tkg_tmp['valid-date'])
            return None
    except Exception:
        # print('read token error: ', e)
        return None


# 토큰 유효시간 체크해서 만료된 토큰이면 재발급처리
def _getBaseHeader():
    if _autoReAuth:
        reAuth()
    return copy.deepcopy(_base_headers)


# 가져오기 : 앱키, 앱시크리트, 종합계좌번호(계좌번호 중 숫자8자리), 계좌상품코드(계좌번호 중 숫자2자리), 토큰, 도메인
def _setTRENV(cfg):
    nt1 = namedtuple(
        "KISEnv",
        ["my_app", "my_sec", "my_acct", "my_prod", "my_htsid", "my_token", "my_url", "my_url_ws"],
    )
    d = {
        "my_app": cfg["my_app"],  # 앱키
        "my_sec": cfg["my_sec"],  # 앱시크리트
        "my_acct": cfg["my_acct"],  # 종합계좌번호(8자리)
        "my_prod": cfg["my_prod"],  # 계좌상품코드(2자리)
        "my_htsid": cfg["my_htsid"],  # HTS ID
        "my_token": cfg["my_token"],  # 토큰
        "my_url": cfg[
            "my_url"
        ],  # 실전 도메인 (https://openapi.koreainvestment.com:9443)
        "my_url_ws": cfg["my_url_ws"],
    }  # 모의 도메인 (https://openapivts.koreainvestment.com:29443)

    # print(cfg['my_app'])
    global _TRENV
    _TRENV = nt1(**d)


def isPaperTrading():  # 모의투자 매매
    return _isPaper


# 실전투자면 'prod', 모의투자면 'vps'를 셋팅 하시기 바랍니다.
def changeTREnv(token_key, svr="prod", product=_cfg["my_prod"]):
    cfg = dict()

    global _isPaper
    if svr == "prod":  # 실전투자
        ak1 = "my_app"  # 실전투자용 앱키
        ak2 = "my_sec"  # 실전투자용 앱시크리트
        _isPaper = False
        _smartSleep = 0.05
    elif svr == "vps":  # 모의투자
        ak1 = "paper_app"  # 모의투자용 앱키
        ak2 = "paper_sec"  # 모의투자용 앱시크리트
        _isPaper = True
        _smartSleep = 0.5

    cfg["my_app"] = _cfg[ak1]
    cfg["my_sec"] = _cfg[ak2]

    if svr == "prod" and product == "01":  # 실전투자 주식투자, 위탁계좌, 투자계좌
        cfg["my_acct"] = _cfg["my_acct_stock"]
    elif svr == "prod" and product == "03":  # 실전투자 선물옵션(파생)
        cfg["my_acct"] = _cfg["my_acct_future"]
    elif svr == "prod" and product == "08":  # 실전투자 해외선물옵션(파생)
        cfg["my_acct"] = _cfg["my_acct_future"]
    elif svr == "prod" and product == "22":  # 실전투자 개인연금저축계좌
        cfg["my_acct"] = _cfg["my_acct_stock"]
    elif svr == "prod" and product == "29":  # 실전투자 퇴직연금계좌
        cfg["my_acct"] = _cfg["my_acct_stock"]
    elif svr == "vps" and product == "01":  # 모의투자 주식투자, 위탁계좌, 투자계좌
        cfg["my_acct"] = _cfg["my_paper_stock"]
    elif svr == "vps" and product == "03":  # 모의투자 선물옵션(파생)
        cfg["my_acct"] = _cfg["my_paper_future"]

    cfg["my_prod"] = product
    cfg["my_htsid"] = _cfg["my_htsid"]
    cfg["my_url"] = _cfg[svr]

    try:
        my_token = _TRENV.my_token
    except AttributeError:
        my_token = ""
    cfg["my_token"] = my_token if token_key else token_key
    cfg["my_url_ws"] = _cfg["ops" if svr == "prod" else "vops"]

    # print(cfg)
    _setTRENV(cfg)


def _getResultObject(json_data):
    _tc_ = namedtuple("res", json_data.keys())

    return _tc_(**json_data)


# Token 발급, 유효기간 1일, 6시간 이내 발급시 기존 token값 유지, 발급시 알림톡 무조건 발송
# 모의투자인 경우  svr='vps', 투자계좌(01)이 아닌경우 product='XX' 변경하세요 (계좌번호 뒤 2자리)
def auth(svr="prod", product=_cfg["my_prod"], url=None):
    p = {
        "grant_type": "client_credentials",
    }
    # 개인 환경파일 "kis_devlp.yaml" 파일을 참조하여 앱키, 앱시크리트 정보 가져오기
    # 개인 환경파일명과 위치는 고객님만 아는 위치로 설정 바랍니다.
    if svr == "prod":  # 실전투자
        ak1 = "my_app"  # 앱키 (실전투자용)
        ak2 = "my_sec"  # 앱시크리트 (실전투자용)
    elif svr == "vps":  # 모의투자
        ak1 = "paper_app"  # 앱키 (모의투자용)
        ak2 = "paper_sec"  # 앱시크리트 (모의투자용)

    # 앱키, 앱시크리트 가져오기
    p["appkey"] = _cfg[ak1]
    p["appsecret"] = _cfg[ak2]

    # 기존 발급된 토큰이 있는지 확인
    saved_token = read_token()  # 기존 발급 토큰 확인
    # print("saved_token: ", saved_token)
    if saved_token is None:  # 기존 발급 토큰 확인이 안되면 발급처리
        url = f"{_cfg[svr]}/oauth2/tokenP"
        res = requests.post(
            url, data=json.dumps(p), headers=_getBaseHeader()
        )  # 토큰 발급
        rescode = res.status_code
        if rescode == 200:  # 토큰 정상 발급
            my_token = _getResultObject(res.json()).access_token  # 토큰값 가져오기
            my_expired = _getResultObject(
                res.json()
            ).access_token_token_expired  # 토큰값 만료일시 가져오기
            save_token(my_token, my_expired)  # 새로 발급 받은 토큰 저장
        else:
            print("Get Authentification token fail!\nYou have to restart your app!!!")
            return
    else:
        my_token = saved_token  # 기존 발급 토큰 확인되어 기존 토큰 사용

    # 발급토큰 정보 포함해서 헤더값 저장 관리, API 호출시 필요
    changeTREnv(my_token, svr, product)

    _base_headers["authorization"] = f"Bearer {my_token}"
    _base_headers["appkey"] = _TRENV.my_app
    _base_headers["appsecret"] = _TRENV.my_sec

    global _last_auth_time
    _last_auth_time = datetime.now()

    if _DEBUG:
        print(f"[{_last_auth_time}] => get AUTH Key completed!")


# end of initialize, 토큰 재발급, 토큰 발급시 유효시간 1일
# 프로그램 실행시 _last_auth_time에 저장하여 유효시간 체크, 유효시간 만료시 토큰 발급 처리
def reAuth(svr="prod", product=_cfg["my_prod"]):
    n2 = datetime.now()
    if (n2 - _last_auth_time).seconds >= 86400:  # 유효시간 1일
        auth(svr, product)


def getEnv():
    return _cfg


def smart_sleep():
    if _DEBUG:
        print(f"[RateLimit] Sleeping {_smartSleep}s ")

    time.sleep(_smartSleep)


def getTREnv():
    return _TRENV


# 주문 API에서 사용할 hash key값을 받아 header에 설정해 주는 함수
# 현재는 hash key 필수 사항아님, 생략가능, API 호출과정에서 변조 우려를 하는 경우 사용
# Input: HTTP Header, HTTP post param
# Output: None
def set_order_hash_key(h, p):
    url = f"{getTREnv().my_url}/uapi/hashkey"  # hashkey 발급 API URL

    res = requests.post(url, data=json.dumps(p), headers=h)
    rescode = res.status_code
    if rescode == 200:
        h["hashkey"] = _getResultObject(res.json()).HASH
    else:
        print("Error:", rescode)


# API 호출 응답에 필요한 처리 공통 함수
class APIResp:
    def __init__(self, resp):
        self._rescode = resp.status_code
        self._resp = resp
        self._header = self._setHeader()
        self._body = self._setBody()
        self._err_code = self._body.msg_cd
        self._err_message = self._body.msg1

    def getResCode(self):
        return self._rescode

    def _setHeader(self):
        fld = dict()
        for x in self._resp.headers.keys():
            if x.islower():
                fld[x] = self._resp.headers.get(x)
        _th_ = namedtuple("header", fld.keys())

        return _th_(**fld)

    def _setBody(self):
        _tb_ = namedtuple("body", self._resp.json().keys())

        return _tb_(**self._resp.json())

    def getHeader(self):
        return self._header

    def getBody(self):
        return self._body

    def getResponse(self):
        return self._resp

    def isOK(self):
        try:
            if self.getBody().rt_cd == "0":
                return True
            else:
                return False
        except:
            return False

    def getErrorCode(self):
        return self._err_code

    def getErrorMessage(self):
        return self._err_message

    def printAll(self):
        print("<Header>")
        for x in self.getHeader()._fields:
            print(f"\t-{x}: {getattr(self.getHeader(), x)}")
        print("<Body>")
        for x in self.getBody()._fields:
            print(f"\t-{x}: {getattr(self.getBody(), x)}")

    def printError(self, url):
        print(
            "-------------------------------\nError in response: ",
            self.getResCode(),
            " url=",
            url,
        )
        print(
            "rt_cd : ",
            self.getBody().rt_cd,
            "/ msg_cd : ",
            self.getErrorCode(),
            "/ msg1 : ",
            self.getErrorMessage(),
        )
        print("-------------------------------")

    # end of class APIResp


class APIRespError(APIResp):
    def __init__(self, status_code, error_text):
        # 부모 생성자 호출하지 않고 직접 초기화
        self.status_code = status_code
        self.error_text = error_text
        self._error_code = str(status_code)
        self._error_message = error_text

    def isOK(self):
        return False

    def getErrorCode(self):
        return self._error_code

    def getErrorMessage(self):
        return self._error_message

    def getBody(self):
        # 빈 객체 리턴 (속성 접근 시 AttributeError 방지)
        class EmptyBody:
            def __getattr__(self, name):
                return None

        return EmptyBody()

    def getHeader(self):
        # 빈 객체 리턴
        class EmptyHeader:
            tr_cont = ""

            def __getattr__(self, name):
                return ""

        return EmptyHeader()

    def printAll(self):
        print(f"=== ERROR RESPONSE ===")
        print(f"Status Code: {self.status_code}")
        print(f"Error Message: {self.error_text}")
        print(f"======================")

    def printError(self, url=""):
        print(f"Error Code : {self.status_code} | {self.error_text}")
        if url:
            print(f"URL: {url}")


########### API call wrapping : API 호출 공통


def _url_fetch(
        api_url, ptr_id, tr_cont, params, appendHeaders=None, postFlag=False, hashFlag=True
):
    url = f"{getTREnv().my_url}{api_url}"

    headers = _getBaseHeader()  # 기본 header 값 정리

    # 추가 Header 설정
    tr_id = ptr_id
    if ptr_id[0] in ("T", "J", "C"):  # 실전투자용 TR id 체크
        if isPaperTrading():  # 모의투자용 TR id 식별
            tr_id = "V" + ptr_id[1:]

    headers["tr_id"] = tr_id  # 트랜젝션 TR id
    headers["custtype"] = "P"  # 일반(개인고객,법인고객) "P", 제휴사 "B"
    headers["tr_cont"] = tr_cont  # 트랜젝션 TR id

    if appendHeaders is not None:
        if len(appendHeaders) > 0:
            for x in appendHeaders.keys():
                headers[x] = appendHeaders.get(x)

    if _DEBUG:
        print("< Sending Info >")
        print(f"URL: {url}, TR: {tr_id}")
        print(f"<header>\n{headers}")
        print(f"<body>\n{params}")

    if postFlag:
        # if (hashFlag): set_order_hash_key(headers, params)
        res = requests.post(url, headers=headers, data=json.dumps(params))
    else:
        res = requests.get(url, headers=headers, params=params)

    if res.status_code == 200:
        ar = APIResp(res)
        if _DEBUG:
            ar.printAll()
        return ar
    else:
        print("Error Code : " + str(res.status_code) + " | " + res.text)
        return APIRespError(res.status_code, res.text)


# auth()
# print("Pass through the end of the line")


########### New - websocket 대응

_base_headers_ws = {
    "content-type": "utf-8",
}


def _getBaseHeader_ws():
    if _autoReAuth:
        reAuth_ws()

    return copy.deepcopy(_base_headers_ws)


def auth_ws(svr="prod", product=_cfg["my_prod"]):
    p = {"grant_type": "client_credentials"}
    if svr == "prod":
        ak1 = "my_app"
        ak2 = "my_sec"
    elif svr == "vps":
        ak1 = "paper_app"
        ak2 = "paper_sec"

    p["appkey"] = _cfg[ak1]
    p["secretkey"] = _cfg[ak2]

    url = f"{_cfg[svr]}/oauth2/Approval"
    res = requests.post(url, data=json.dumps(p), headers=_getBaseHeader())  # 토큰 발급
    rescode = res.status_code
    if rescode == 200:  # 토큰 정상 발급
        approval_key = _getResultObject(res.json()).approval_key
    else:
        print("Get Approval token fail!\nYou have to restart your app!!!")
        return

    changeTREnv(None, svr, product)

    _base_headers_ws["approval_key"] = approval_key

    global _last_auth_time
    _last_auth_time = datetime.now()

    if _DEBUG:
        print(f"[{_last_auth_time}] => get AUTH Key completed!")


def reAuth_ws(svr="prod", product=_cfg["my_prod"]):
    n2 = datetime.now()
    if (n2 - _last_auth_time).seconds >= 86400:
        auth_ws(svr, product)


def data_fetch(tr_id, tr_type, params, appendHeaders=None) -> dict:
    headers = _getBaseHeader_ws()  # 기본 header 값 정리

    headers["tr_type"] = tr_type
    headers["custtype"] = "P"

    if appendHeaders is not None:
        if len(appendHeaders) > 0:
            for x in appendHeaders.keys():
                headers[x] = appendHeaders.get(x)

    if _DEBUG:
        print("< Sending Info >")
        print(f"TR: {tr_id}")
        print(f"<header>\n{headers}")

    inp = {
        "tr_id": tr_id,
    }
    inp.update(params)

    return {"header": headers, "body": {"input": inp}}


# iv, ekey, encrypt 는 각 기능 메소드 파일에 저장할 수 있도록 dict에서 return 하도록
def system_resp(data):
    isPingPong = False
    isUnSub = False
    isOk = False
    tr_msg = None
    tr_key = None
    encrypt, iv, ekey = None, None, None

    rdic = json.loads(data)

    tr_id = rdic["header"]["tr_id"]
    if tr_id != "PINGPONG":
        tr_key = rdic["header"]["tr_key"]
        encrypt = rdic["header"]["encrypt"]
    if rdic.get("body", None) is not None:
        isOk = True if rdic["body"]["rt_cd"] == "0" else False
        tr_msg = rdic["body"]["msg1"]
        # 복호화를 위한 key 를 추출
        if "output" in rdic["body"]:
            iv = rdic["body"]["output"]["iv"]
            ekey = rdic["body"]["output"]["key"]
        isUnSub = True if tr_msg[:5] == "UNSUB" else False
    else:
        isPingPong = True if tr_id == "PINGPONG" else False

    nt2 = namedtuple(
        "SysMsg",
        [
            "isOk",
            "tr_id",
            "tr_key",
            "isUnSub",
            "isPingPong",
            "tr_msg",
            "iv",
            "ekey",
            "encrypt",
        ],
    )
    d = {
        "isOk": isOk,
        "tr_id": tr_id,
        "tr_key": tr_key,
        "tr_msg": tr_msg,
        "isUnSub": isUnSub,
        "isPingPong": isPingPong,
        "iv": iv,
        "ekey": ekey,
        "encrypt": encrypt,
    }

    return nt2(**d)


def aes_cbc_base64_dec(key, iv, cipher_text):
    if key is None or iv is None:
        raise AttributeError("key and iv cannot be None")

    cipher = AES.new(key.encode("utf-8"), AES.MODE_CBC, iv.encode("utf-8"))
    return bytes.decode(unpad(cipher.decrypt(b64decode(cipher_text)), AES.block_size))


#####
open_map: dict = {}


def add_open_map(
        name: str,
        request: Callable[[str, str, ...], (dict, list[str])],
        data: str | list[str],
        kwargs: dict = None,
):
    if open_map.get(name, None) is None:
        open_map[name] = {
            "func": request,
            "items": [],
            "kwargs": kwargs,
        }

    if type(data) is list:
        open_map[name]["items"] += data
    elif type(data) is str:
        open_map[name]["items"].append(data)


data_map: dict = {}


def add_data_map(
        tr_id: str,
        columns: list = None,
        encrypt: str = None,
        key: str = None,
        iv: str = None,
):
    if data_map.get(tr_id, None) is None:
        data_map[tr_id] = {"columns": [], "encrypt": False, "key": None, "iv": None}

    if columns is not None:
        data_map[tr_id]["columns"] = columns

    if encrypt is not None:
        data_map[tr_id]["encrypt"] = encrypt

    if key is not None:
        data_map[tr_id]["key"] = key

    if iv is not None:
        data_map[tr_id]["iv"] = iv


class KISWebSocket:
    api_url: str = ""
    on_result: Callable[
        [websockets.ClientConnection, str, pd.DataFrame, dict], None
    ] = None
    result_all_data: bool = False

    retry_count: int = 0
    amx_retries: int = 0

    # init
    def __init__(self, api_url: str, max_retries: int = 3):
        self.api_url = api_url
        self.max_retries = max_retries

    # private
    async def __subscriber(self, ws: websockets.ClientConnection):
        async for raw in ws:
            logging.info("received message >> %s" % raw)
            show_result = False

            df = pd.DataFrame()

            if raw[0] in ["0", "1"]:
                d1 = raw.split("|")
                if len(d1) < 4:
                    raise ValueError("data not found...")

                tr_id = d1[1]

                dm = data_map[tr_id]
                d = d1[3]
                if dm.get("encrypt", None) == "Y":
                    d = aes_cbc_base64_dec(dm["key"], dm["iv"], d)

                df = pd.read_csv(
                    StringIO(d), header=None, sep="^", names=dm["columns"], dtype=object
                )

                show_result = True

            else:
                rsp = system_resp(raw)

                tr_id = rsp.tr_id
                add_data_map(
                    tr_id=rsp.tr_id, encrypt=rsp.encrypt, key=rsp.ekey, iv=rsp.iv
                )

                if rsp.isPingPong:
                    print(f"### RECV [PINGPONG] [{raw}]")
                    await ws.pong(raw)
                    print(f"### SEND [PINGPONG] [{raw}]")

                if self.result_all_data:
                    show_result = True

            if show_result is True and self.on_result is not None:
                self.on_result(ws, tr_id, df, data_map[tr_id])

    async def __runner(self):
        if len(open_map.keys()) > 40:
            raise ValueError("Subscription's max is 40")

        url = f"{getTREnv().my_url_ws}{self.api_url}"

        while self.retry_count < self.max_retries:
            try:
                async with websockets.connect(url) as ws:
                    # request subscribe
                    for name, obj in open_map.items():
                        await self.send_multiple(
                            ws, obj["func"], "1", obj["items"], obj["kwargs"]
                        )

                    # subscriber
                    await asyncio.gather(
                        self.__subscriber(ws),
                    )
            except Exception as e:
                print("Connection exception >> ", e)
                self.retry_count += 1
                await asyncio.sleep(1)

    # func
    @classmethod
    async def send(
            cls,
            ws: websockets.ClientConnection,
            request: Callable[[str, str, ...], (dict, list[str])],
            tr_type: str,
            data: str,
            kwargs: dict = None,
    ):
        k = {} if kwargs is None else kwargs
        msg, columns = request(tr_type, data, **k)

        add_data_map(tr_id=msg["body"]["input"]["tr_id"], columns=columns)

        logging.info("send message >> %s" % json.dumps(msg))

        await ws.send(json.dumps(msg))
        smart_sleep()

    async def send_multiple(
            self,
            ws: websockets.ClientConnection,
            request: Callable[[str, str, ...], (dict, list[str])],
            tr_type: str,
            data: list | str,
            kwargs: dict = None,
    ):
        if type(data) is str:
            await self.send(ws, request, tr_type, data, kwargs)
        elif type(data) is list:
            for d in data:
                await self.send(ws, request, tr_type, d, kwargs)
        else:
            raise ValueError("data must be str or list")

    @classmethod
    def subscribe(
            cls,
            request: Callable[[str, str, ...], (dict, list[str])],
            data: list | str,
            kwargs: dict = None,
    ):
        add_open_map(request.__name__, request, data, kwargs)

    def unsubscribe(
            self,
            ws: websockets.ClientConnection,
            request: Callable[[str, str, ...], (dict, list[str])],
            data: list | str,
    ):
        self.send_multiple(ws, request, "2", data)

    # start
    def start(
            self,
            on_result: Callable[
                [websockets.ClientConnection, str, pd.DataFrame, dict], None
            ],
            result_all_data: bool = False,
    ):
        self.on_result = on_result
        self.result_all_data = result_all_data
        try:
            asyncio.run(self.__runner())
        except KeyboardInterrupt:
            print("Closing by KeyboardInterrupt")

잔고조회

In [ ]:
def get_stock_balance() -> dict[str, int]:
    """주식 잔고조회"""
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-balance"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8434R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "",
        "INQR_DVSN": "02",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": "",
        "CTX_AREA_NK100": "",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output1" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[주식 잔고조회 실패] {msg}")
        raise ValueError(f"주식 잔고 조회 실패: {msg}")

    stock_list = data["output1"]
    evaluation = data.get("output2", [])
    stock_dict: dict[str, int] = {}

    send_message("====주식 보유잔고====")
    for stock in stock_list:
        try:
            qty = int(stock.get("hldg_qty", "0"))
        except (TypeError, ValueError):
            qty = 0
        if qty > 0:
            pdno = stock.get("pdno", "")
            stock_dict[pdno] = qty
            send_message(f"{stock.get('prdt_name', '미상')}({pdno}): {qty}주")
            time.sleep(0.1)

    if evaluation:
        eval0 = evaluation[0]
        send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
        time.sleep(0.1)
        send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
        time.sleep(0.1)
        send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
        time.sleep(0.1)
    send_message("=====================")

    return stock_dict

def get_balance(price_code: str = "005930", order_price: str = "65500") -> int:
    """현금 잔고조회"""
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-psbl-order"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8908R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": price_code,
        "ORD_UNPR": order_price,
        "ORD_DVSN": "01",
        "CMA_EVLU_AMT_ICLD_YN": "Y",
        "OVRS_ICLD_YN": "Y",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[현금 잔고조회 실패] {msg}")
        raise ValueError(f"현금 잔고 조회 실패: {msg}")

    cash = int(data["output"]["ord_psbl_cash"])
    send_message(f"주문 가능 현금 잔고: {cash:,}원")
    return cash


my_money = get_stock_balance()
print(my_money)

my_cash = get_balance()
print(f"현금 주문 가능 금액: {my_cash:,}원")

NameError: name 'ACCESS_TOKEN' is not defined

현재가 조회

In [ ]:
# 현재가 조회        
def get_current_price(stock_no: str = "005930"):
    """
    주어진 종목코드(stock_no)의 현재가(실시간 주식 가격)를 조회합니다.

    Args:
        stock_no (str): 조회할 종목의 코드. 기본값은 "005930"(삼성전자).

    Returns:
        str | None: 현재가(문자열) 또는 조회 실패 시 None을 반환합니다.

    Raises:
        RuntimeError: ACCESS_TOKEN 발급에 실패했을 때 발생합니다.

    사용 예시:
        price = get_current_price("005930")
    """
    global ACCESS_TOKEN

    # 토큰 준비
    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")
    
    PATH = "uapi/domestic-stock/v1/quotations/inquire-price"
    URL = f"{URL_BASE}/{PATH}"

    # 헤더 설정
    headers = {
        "Content-Type": "application/json", 
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010100"
    }

    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": stock_no
    }

    # 호출
    res = requests.get(URL, headers=headers, params=params)

    if res.status_code == 200 and res.json()["rt_cd"] == "0":
        return res.json()['output']['stck_prpr']
    else:
        print("Error Code : " + str(res.status_code) + " | " + res.text)
        send_message(f"Error Code : {str(res.status_code)} | {res.text}")
        return None
    
    
a = get_current_price()
print(a)

100600

In [ ]:
{'stck_bsop_date': '20251114', 'stck_oprc': '99000', 'stck_hgpr': '99600', 'stck_lwpr': '97200', 'stck_clpr': '97200', 'acml_vol': '21806342', 'prdy_vrss_vol_rate': '4.64', 'prdy_vrss': '-5600', 'prdy_vrss_sign': '5', 'prdy_ctrt': '-5.45', 'hts_frgn_ehrt': '52.23', 'frgn_ntby_qty': '-6572881', 'flng_cls_code': '00', 'acml_prtt_rate': '0.00'}

In [ ]:
PATH = "uapi/domestic-stock/v1/quotations/inquire-daily-price"
URL = f"{URL_BASE}/{PATH}"

headers = {
    "Content-Type": "application/json",
    "authorization": f"Bearer {ACCESS_TOKEN}",
    "appKey": APP_KEY,
    "appSecret": APP_SECRET,
    "tr_id": "FHKST01010400",
}
params = {
    "fid_cond_mrkt_div_code": "J",
    "fid_input_iscd": "005930",
    "fid_org_adj_prc": "1",
    "fid_period_div_code": "D",
}

res = requests.get(URL, headers=headers, params=params, timeout=10)
data = res.json()
data_keys = list(data['output'][0].keys())
for i in data['output']:
    pass
# print(data['output'][0]['stck_bsop_date'])
# print(data['output'][0]['stck_oprc'])

print(data['output'][0]['stck_clpr'])

print(data['output'][0])

100600
{'stck_bsop_date': '20251117', 'stck_oprc': '99800', 'stck_hgpr': '101000', 'stck_lwpr': '99500', 'stck_clpr': '100600', 'acml_vol': '17192584', 'prdy_vrss_vol_rate': '-21.16', 'prdy_vrss': '3400', 'prdy_vrss_sign': '2', 'prdy_ctrt': '3.50', 'hts_frgn_ehrt': '52.29', 'frgn_ntby_qty': '3661497', 'flng_cls_code': '00', 'acml_prtt_rate': '1.00'}

In [ ]:
# import pandas as pd
# import yfinance as yf

# # 1. 데이터 불러오기
# df = yf.download('005930.KS', start="2024-01-01", end="2024-12-31")
# print(df)
# # 2. RSI, MACD 지표 계산 함수 정의
# def compute_rsi(series, period=7):
#     delta = series.diff()
#     gain = delta.clip(lower=0)
#     loss = -delta.clip(upper=0)
#     avg_gain = gain.rolling(window=period, min_periods=period).mean()
#     avg_loss = loss.rolling(window=period, min_periods=period).mean()
#     rs = avg_gain / avg_loss
#     rsi = 100 - (100 / (1 + rs))
#     return rsi

# def compute_macd(series, fast=8, slow=17, signal=5):
#     """
#     예시 조합 1: (5, 13, 3) → 빠른 반응, 스캘핑에 적합
#     예시 조합 2: (8, 17, 5) → 약간의 안정성 확보, 데이 트레이딩에 적합
#     """
#     ema_fast = series.ewm(span=fast, adjust=False).mean()
#     ema_slow = series.ewm(span=slow, adjust=False).mean()
#     macd = ema_fast - ema_slow
#     macd_signal = macd.ewm(span=signal, adjust=False).mean()
#     return macd, macd_signal

# # 3. 각 컬럼 생성
# df['RSI'] = compute_rsi(df['Close'])
# df['MACD'], df['Signal'] = compute_macd(df['Close'])

# # 4. trading_signal 함수 수정 (iloc/lon으로 스칼라값만 비교하도록 에러 수정)
# def trading_signal_fixed(df, rsi_column='RSI', macd_column='MACD', signal_column='Signal'):
#     """
#     df: DataFrame with 'RSI', 'MACD', 'Signal' columns
#     return: pd.Series of 'Buy', 'Sell', or 'Hold'
#     """
#     signals = []
#     for i in range(1, len(df)):
#         # .iloc[]로 스칼라값 추출 → Series가 아닌 float/np.nan
#         rsi = df[rsi_column].iloc[i]
#         macd = df[macd_column].iloc[i]
#         macd_prev = df[macd_column].iloc[i-1]
#         signal = df[signal_column].iloc[i]
#         signal_prev = df[signal_column].iloc[i-1]
        
#         if pd.isna(rsi) or pd.isna(macd) or pd.isna(macd_prev) or pd.isna(signal) or pd.isna(signal_prev):
#             signals.append('Hold')
#             continue

#         # Buy condition
#         if (rsi < 30) and (macd > signal) and (macd_prev < signal_prev):
#             signals.append('Buy')
#         # Sell condition
#         elif (rsi > 70) and (macd < signal) and (macd_prev > signal_prev):
#             signals.append('Sell')
#         else:
#             signals.append('Hold')
#     signals = ['Hold'] + signals    # 첫 데이터는 비교 불가이므로 Hold
#     return pd.Series(signals, index=df.index)

# df['Trade_signal'] = trading_signal_fixed(df, 'RSI', 'MACD', 'Signal')

목표가 지정 함수

In [ ]:
# def get_target_price(code="005930"):
#     """변동성 돌파 전략으로 매수 목표가 조회"""
#     prev_day_info = get_prev_day_high_low()
#     stck_oprc = int(prev_day_info['stck_oprc']) #오늘 시가
#     stck_hgpr = int(prev_day_info['prev_high']) #전일 고가
#     stck_lwpr = int(prev_day_info['prev_low']) #전일 저가
#     target_price = stck_oprc + (stck_hgpr - stck_lwpr) * 0.5
#     return target_price

# print(get_target_price())

101000.0

In [ ]:
# RSI, CDMA 활용한 수정
def get_target_price(code="005930"):
    """변동성 돌파 전략으로 매수 목표가 조회"""
    prev_day_info = get_prev_day_high_low()
    stck_oprc = int(prev_day_info['stck_oprc']) #오늘 시가
    stck_hgpr = int(prev_day_info['prev_high']) #전일 고가
    stck_lwpr = int(prev_day_info['prev_low']) #전일 저가
    target_price = stck_oprc + (stck_hgpr - stck_lwpr) * 0.5
    return target_price

print(get_target_price())

매매 코드

In [ ]:
# def buy(code="005930", qty="1"):
#     """주식 시장가 매수"""  
#     PATH = "uapi/domestic-stock/v1/trading/order-cash"
#     URL = f"{URL_BASE}/{PATH}"
#     data = {
#         "CANO": CANO,
#         "ACNT_PRDT_CD": ACNT_PRDT_CD,
#         "PDNO": code,
#         "ORD_DVSN": "01",
#         "ORD_QTY": str(int(qty)),
#         "ORD_UNPR": "0",
#     }
#     headers = {"Content-Type":"application/json", 
#         "authorization":f"Bearer {ACCESS_TOKEN}",
#         "appKey":APP_KEY,
#         "appSecret":APP_SECRET,
#         "tr_id":"TTTC0802U",
#         "custtype":"P",
#         "hashkey" : hashkey(data)
#     }
#     res = requests.post(URL, headers=headers, data=json.dumps(data))
#     if res.json()['rt_cd'] == '0':
#         send_message(f"[매수 성공]{str(res.json())}")
#         return True
#     else:
#         send_message(f"[매수 실패]{str(res.json())}")
#         return False

# def sell(code="005930", qty="1"):
#     """주식 시장가 매도"""
#     PATH = "uapi/domestic-stock/v1/trading/order-cash"
#     URL = f"{URL_BASE}/{PATH}"
#     data = {
#         "CANO": CANO,
#         "ACNT_PRDT_CD": ACNT_PRDT_CD,
#         "PDNO": code,
#         "ORD_DVSN": "01",
#         "ORD_QTY": qty,
#         "ORD_UNPR": "0",
#     }
#     headers = {"Content-Type":"application/json", 
#         "authorization":f"Bearer {ACCESS_TOKEN}",
#         "appKey":APP_KEY,
#         "appSecret":APP_SECRET,
#         "tr_id":"TTTC0801U",
#         "custtype":"P",
#         "hashkey" : hashkey(data)
#     }
#     res = requests.post(URL, headers=headers, data=json.dumps(data))
#     if res.json()['rt_cd'] == '0':
#         send_message(f"[매도 성공]{str(res.json())}")
#         return True
#     else:
#         send_message(f"[매도 실패]{str(res.json())}")
#         return False

In [ ]:
# 매수 코드 작성
def buy(code="005930", qty="1"):
    """주식 시장가 매수"""  
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": str(int(qty)),
        "ORD_UNPR": "0",
    }
    headers = {
        "Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0012U",    # (구)TTTC0802U → (신)TTTC0012U
        "custtype":"P",
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    if res.json()['rt_cd'] == '0':
        send_message(f"[매수 성공]{str(res.json())}")
        return True
    else:
        send_message(f"[매수 실패]{str(res.json())}")
        return False
    
# buy(code = "092200")

In [ ]:
# 매도 코드 작성
def sell(code="005930", qty="1"):
    """주식 시장가 매도"""
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": qty,
        "ORD_UNPR": "0",
    }
    headers = {
        "Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0011U",    # (구)TTTC0801U → (신)TTTC0011U
        "custtype":"P",
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    if res.json()['rt_cd'] == '0':
        send_message(f"[매도 성공]{str(res.json())}")
        return True
    else:
        send_message(f"[매도 실패]{str(res.json())}")
        return False
    
    
    
sell(code = "036630")

{'content': "[2025-11-14 09:22:04] [매도 성공]{'rt_cd': '0', 'msg_cd': 'APBK0013', 'msg1': '주문 전송 완료 되었습니다.', 'output': {'KRX_FWDG_ORD_ORGNO': '91250', 'ODNO': '0007194100', 'ORD_TMD': '092204', 'SOR_ODNO': ''}}"}

True

자동매매 시작

In [ ]:
# 자동매매 시작
try:
    ACCESS_TOKEN = get_access_token()

    symbol_list = ["005930","092200","035720","000660"] # 매수 희망 종목 리스트
    bought_list = [] # 매수 완료된 종목 리스트
    total_cash = get_balance() # 보유 현금 조회
    stock_dict = get_stock_balance() # 보유 주식 조회
    for sym in stock_dict.keys():
        bought_list.append(sym)
    target_buy_count = 3 # 매수할 종목 수
    buy_percent = 0.33 # 종목당 매수 금액 비율
    buy_amount = total_cash * buy_percent  # 종목별 주문 금액 계산
    soldout = False

    send_message("===국내 주식 자동매매 프로그램을 시작합니다===")
    while True:
        t_now = datetime.now()
        t_9 = t_now.replace(hour=9, minute=0, second=0, microsecond=0)
        t_start = t_now.replace(hour=9, minute=5, second=0, microsecond=0)
        t_sell = t_now.replace(hour=15, minute=15, second=0, microsecond=0)
        t_exit = t_now.replace(hour=15, minute=20, second=0,microsecond=0)
        today = datetime.today().weekday()
        if today == 5 or today == 6:  # 토요일이나 일요일이면 자동 종료
            send_message("주말이므로 프로그램을 종료합니다.")
            break
        if t_9 < t_now < t_start and soldout == False: # 잔여 수량 매도
            for sym, qty in stock_dict.items():
                sell(sym, qty)
            soldout == True
            bought_list = []
            stock_dict = get_stock_balance()
        if t_start < t_now < t_sell :  # AM 09:05 ~ PM 03:15 : 매수
            for sym in symbol_list:
                if len(bought_list) < target_buy_count:
                    if sym in bought_list:
                        continue
                    target_price = get_target_price(sym)
                    current_price = get_current_price(sym)
                    if target_price < current_price:
                        buy_qty = 0  # 매수할 수량 초기화
                        buy_qty = int(buy_amount // current_price)
                        if buy_qty > 0:
                            send_message(f"{sym} 목표가 달성({target_price} < {current_price}) 매수를 시도합니다.")
                            result = buy(sym, buy_qty)
                            if result:
                                soldout = False
                                bought_list.append(sym)
                                get_stock_balance()
                    time.sleep(1)
            time.sleep(1)
            if t_now.minute == 30 and t_now.second <= 5: 
                get_stock_balance()
                time.sleep(5)
        if t_sell < t_now < t_exit:  # PM 03:15 ~ PM 03:20 : 일괄 매도
            if soldout == False:
                stock_dict = get_stock_balance()
                for sym, qty in stock_dict.items():
                    sell(sym, qty)
                soldout = True
                bought_list = []
                time.sleep(1)
        if t_exit < t_now:  # PM 03:20 ~ :프로그램 종료
            send_message("프로그램을 종료합니다.")
            break
except Exception as e:
    send_message(f"[오류 발생]{e}")
    time.sleep(1)

백테스트

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# 1. 데이터 불러오기 (CSV 또는 API)
df = pd.read_csv('stock_data.csv')  # 시가, 고가, 저가, 종가, 거래량 포함

# 2. 전략 파라미터 설정
K = 0.5  # 변동성 계수
fee = 0.001  # 거래 수수료

# 3. 목표가 계산
df['range'] = df['high'].shift(1) - df['low'].shift(1)
df['target'] = df['open'] + df['range'] * K

# 4. 수익률 계산
df['buy'] = df['high'] > df['target']
df['return'] = 0
df.loc[df['buy'], 'return'] = df['close'] / df['target'] - fee
df.loc[~df['buy'], 'return'] = 1

# 5. 누적 수익률
df['cum_return'] = df['return'].cumprod()

# 6. 시각화
plt.figure(figsize=(12,6))
plt.plot(df['date'], df['cum_return'])
plt.title('변동성 돌파 전략 누적 수익률')
plt.xlabel('Date')
plt.ylabel('Cumulative Return')
plt.grid()
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'stock_data.csv'

RSI, MACD

In [ ]:
# 종가 데이터 반환 함수 
def get_close_price(code: str = "005930", days: int = 14) -> dict | None:

    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급 실패")

    PATH = "uapi/domestic-stock/v1/quotations/inquire-daily-price"
    URL = f"{URL_BASE}/{PATH}"

    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010400",
    }
    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": code,
        "fid_org_adj_prc": "1",
        "fid_period_div_code": "D",
    }

    res = requests.get(URL, headers=headers, params=params, timeout=10)
    if res.status_code != 200:
        print("API 호출 실패")
        print("res.status_code: ", res.status_code)
        return None

    data = res.json()
    rows = data.get("output", []) or []
    if not rows:
        return None

    today_str = datetime.today().strftime("%Y%m%d")
    # 전일: 오늘보다 과거 날짜 중 가장 최근
    prev = None
    clpr_tmp = []
    count = days
    for row in rows:
        d = row.get("stck_bsop_date")
        # print(f"{count}", "stck_bsop_date", d)
        if d and d < today_str:
            if count != 0:
                clpr_tmp.append(row.get("stck_clpr"))
                count -= 1
            else: 
                break
    # clpr_list = clpr_tmp
    # print(clpr_list)
    clpr_list = []
    while clpr_tmp:
        tmp = clpr_tmp.pop()
        clpr_list.append(int(tmp))
    
    return clpr_list

get_close_price()

[100500,
 104100,
 107500,
 111100,
 104900,
 100600,
 99200,
 97900,
 100600,
 103500,
 103100,
 102800,
 97200,
 100600]

In [ ]:
# import pandas as pd

# def RSI(prev_close: pd.Series, period: int = 14) -> pd.Series:
#     """
#     전날 종가 데이터(일봉)을 받아 RSI(Relative Strength Index) 값을 반환합니다.
#     :param prev_close: 전날 종가의 pd.Series (일봉 기준)
#     :param period: RSI를 계산할 기간 (기본값 14)
#     :return: RSI 값의 pd.Series
#     """
#     delta = prev_close.diff()
#     gain = delta.where(delta > 0, 0)
#     loss = -delta.where(delta < 0, 0)
#     print(f"gain = {gain}, loss = {loss}")
#     avg_gain = gain.rolling(window=period, min_periods=period).mean()
#     avg_loss = loss.rolling(window=period, min_periods=period).mean()

#     rs = avg_gain / avg_loss
#     rsi = 100 - (100 / (1 + rs))
    
#     return rsi


# clpr = pd.Series(get_close_price())
# print(RSI(clpr))

In [ ]:
def MACD(series: pd.Series, short_period: int = 12, long_period: int = 26, signal_period: int = 9):
    """
    MACD 값을 출력하는 함수입니다.
    :param series: 가격(종가 등)의 pd.Series
    :param short_period: 단기 EMA 기간 (기본값 12)
    :param long_period: 장기 EMA 기간 (기본값 26)
    :param signal_period: 시그널 EMA 기간 (기본값 9)
    :return: MACD 라인, 시그널 라인, MACD 히스토그램 (모두 pd.Series)
    """
    ema_short = series.ewm(span=short_period, min_periods=short_period).mean()
    ema_long = series.ewm(span=long_period, min_periods=long_period).mean()
    macd = ema_short - ema_long
    signal = macd.ewm(span=signal_period, min_periods=signal_period).mean()
    macd_hist = macd - signal
    return macd, signal, macd_hist

# 예시 출력 (series 자리에 종가 데이터 전달)
# macd_line, signal_line, macd_hist = MACD(df['close'])
# print(macd_line)
# print(signal_line)
# print(macd_hist)

# ai 추천 시스템

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np
from ta.momentum import RSIIndicator
from ta.trend import MACD
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# 1. 데이터 수집
tickers = ['AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN']
data = {}
for ticker in tickers:
    df = yf.download(ticker, period='1y')
    df['Ticker'] = ticker
    data[ticker] = df

df_all = pd.concat(data.values())

# 2. 기술적 지표 생성 함수
def add_indicators(df):
    # MA20, MA60 모두 아래처럼 수정
    df['MA20'] = df['Close']
    if isinstance(df['MA20'], pd.DataFrame):
        df['MA20'] = df['MA20'].iloc[:, 0]
    df['MA20'] = df['MA20'].rolling(window=20).mean()

    df['MA60'] = df['Close']
    if isinstance(df['MA60'], pd.DataFrame):
        df['MA60'] = df['MA60'].iloc[:, 0]
    df['MA60'] = df['MA60'].rolling(window=60).mean()
    df['RSI'] = RSIIndicator(close=df['Close']).rsi()
    macd = MACD(close=df['Close'])
    df['MACD'] = macd.macd_diff()
    df['Return'] = df['Close'].pct_change().shift(-1)
    df['Target'] = (df['Return'] > 0).astype(int)
    return df.dropna()

# 3. 지표 적용
df_all = df_all.groupby('Ticker').apply(add_indicators).reset_index(drop=True)

# 4. 모델 학습
features = ['MA20', 'MA60', 'RSI', 'MACD']
X = df_all[features]
y = df_all['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

# 5. 예측 및 추천
df_all['Predicted_Prob'] = model.predict_proba(X)[:, 1]
latest = df_all.groupby('Ticker').tail(1)
recommend = latest[latest['Predicted_Prob'] > 0.55][['Ticker', 'Predicted_Prob']]

print("📈 추천 종목:")
print(recommend.sort_values(by='Predicted_Prob', ascending=False))

/tmp/ipykernel_2952/3679790335.py:14: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period='1y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2952/3679790335.py:14: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period='1y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2952/3679790335.py:14: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period='1y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2952/3679790335.py:14: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period='1y')
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2952/3679790335.py:14: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period='1y')
[*********************100%***********************]  1 of 1 completed

ValueError: Cannot set a DataFrame with multiple columns to the single column MA20

https://www.youtube.com/watch?v=f2BXwjNb_2o

1. 1차 상승 거감 매매
2. 장대 양봉 + 거감 조정
- 대전제:

# 모히또 모듈
https://wikidocs.net/book/7845

In [ ]:
pip install mojito2

Collecting mojito2
  Downloading mojito2-0.1.6-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: requests in /home/mycom/.local/lib/python3.10/site-packages (from mojito2) (2.32.3)
Requirement already satisfied: websockets in /home/mycom/miniconda3/lib/python3.10/site-packages (from mojito2) (15.0.1)
Requirement already satisfied: pycryptodome in /home/mycom/miniconda3/lib/python3.10/site-packages (from mojito2) (3.23.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/mycom/.local/lib/python3.10/site-packages (from requests->mojito2) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /home/mycom/miniconda3/lib/python3.10/site-packages (from requests->mojito2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/mycom/miniconda3/lib/python3.10/site-packages (from requests->mojito2) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/mycom/miniconda3/lib/python3.10/site-packages (from requests->mojito2) (2025.1.31)
Downloading mojito2-0.1.6-py3-none-any.whl (14 kB)
Installing collected packages: mojito2
Successfully installed mojito2-0.1.6
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import mojito
import pprint

mojito.__version__

'0.1.6'

In [ ]:
# yaml 파일 로딩
with open('config.yaml', encoding='UTF-8') as f:
    _cfg = yaml.load(f, Loader=yaml.FullLoader)
APP_KEY = _cfg['APP_KEY']
APP_SECRET = _cfg['APP_SECRET']
ACCESS_TOKEN = ""
CANO = _cfg['CANO']
ACNT_PRDT_CD = _cfg['ACNT_PRDT_CD']
DISCORD_WEBHOOK_URL = _cfg['DISCORD_WEBHOOK_URL']
URL_BASE = _cfg['URL_BASE']



broker = mojito.KoreaInvestment(
    api_key=APP_KEY,
    api_secret=APP_SECRET,
    acc_no=CANO+"-"+ACNT_PRDT_CD
)

print(broker)

<mojito.koreainvestment.KoreaInvestment object at 0x7fb48c63ca00>

In [ ]:
resp = broker.fetch_price("005930")
pprint.pprint(resp)

{'msg1': '정상처리 되었습니다.',
 'msg_cd': 'MCA00000',
 'output': {'acml_tr_pbmn': '1136775319150',
            'acml_vol': '11490316',
            'aspr_unit': '100',
            'bps': '57930.00',
            'bstp_kor_isnm': '전기·전자',
            'clpr_rang_cont_yn': 'N',
            'cpfn': '7780',
            'cpfn_cnnm': '7,780 억',
            'crdt_able_yn': 'Y',
            'd250_hgpr': '112400',
            'd250_hgpr_date': '20251104',
            'd250_hgpr_vrss_prpr_rate': '-11.92',
            'd250_lwpr': '49900',
            'd250_lwpr_date': '20241114',
            'd250_lwpr_vrss_prpr_rate': '98.40',
            'dmrs_val': '104450',
            'dmsp_val': '102550',
            'dryy_hgpr_date': '20251104',
            'dryy_hgpr_vrss_prpr_rate': '-11.92',
            'dryy_lwpr_date': '20250203',
            'dryy_lwpr_vrss_prpr_rate': '94.88',
            'elw_pblc_yn': 'Y',
            'eps': '4950.00',
            'fcam_cnnm': '100',
            'frgn_hldn_qty': '3098479227',
            'frgn_ntby_qty': '0',
            'grmn_rate_cls_code': '40',
            'hts_avls': '5860442',
            'hts_deal_qty_unit_val': '1',
            'hts_frgn_ehrt': '52.34',
            'invt_caful_yn': 'N',
            'iscd_stat_cls_code': '55',
            'last_ssts_cntg_qty': '1004180',
            'lstn_stcn': '5919637922',
            'mang_issu_cls_code': 'N',
            'marg_rate': '20.00',
            'mrkt_warn_cls_code': '00',
            'oprc_rang_cont_yn': 'N',
            'ovtm_vi_cls_code': 'N',
            'pbr': '1.71',
            'per': '20.00',
            'pgtr_ntby_qty': '-3079806',
            'prdy_ctrt': '-3.70',
            'prdy_vrss': '-3800',
            'prdy_vrss_sign': '5',
            'prdy_vrss_vol_rate': '55.14',
            'pvt_frst_dmrs_prc': '103900',
            'pvt_frst_dmsp_prc': '102000',
            'pvt_pont_val': '103100',
            'pvt_scnd_dmrs_prc': '105000',
            'pvt_scnd_dmsp_prc': '101200',
            'rprs_mrkt_kor_name': 'KOSPI200',
            'rstc_wdth_prc': '30800',
            'short_over_yn': 'N',
            'sltr_yn': 'N',
            'ssts_yn': 'Y',
            'stac_month': '12',
            'stck_dryy_hgpr': '112400',
            'stck_dryy_lwpr': '50800',
            'stck_fcam': '100',
            'stck_hgpr': '99600',
            'stck_llam': '72000',
            'stck_lwpr': '98500',
            'stck_mxpr': '133600',
            'stck_oprc': '99000',
            'stck_prpr': '99000',
            'stck_sdpr': '102800',
            'stck_shrn_iscd': '005930',
            'stck_sspr': '78120',
            'temp_stop_yn': 'N',
            'vi_cls_code': 'N',
            'vol_tnrt': '0.19',
            'w52_hgpr': '112400',
            'w52_hgpr_date': '20251104',
            'w52_hgpr_vrss_prpr_ctrt': '-11.92',
            'w52_lwpr': '49900',
            'w52_lwpr_date': '20241114',
            'w52_lwpr_vrss_prpr_ctrt': '98.40',
            'wghn_avrg_stck_prc': '98933.21',
            'whol_loan_rmnd_rate': '0.27'},
 'rt_cd': '0'}

In [ ]:
print("Open : ", resp['output']['stck_oprc'])   # 시가
print("High : ", resp['output']['stck_hgpr'])    # 고가
print("Low  : ", resp['output']['stck_lwpr'])     # 저가
print("Close: ", resp['output']['stck_prpr'])    # 종가

Open :  99000
High :  99600
Low  :  98500
Close:  99000

In [ ]:
a = sorted(list(resp['output'].keys()))
b = resp['output']
pprint.pprint(a)

['acml_tr_pbmn',
 'acml_vol',
 'aspr_unit',
 'bps',
 'bstp_kor_isnm',
 'clpr_rang_cont_yn',
 'cpfn',
 'cpfn_cnnm',
 'crdt_able_yn',
 'd250_hgpr',
 'd250_hgpr_date',
 'd250_hgpr_vrss_prpr_rate',
 'd250_lwpr',
 'd250_lwpr_date',
 'd250_lwpr_vrss_prpr_rate',
 'dmrs_val',
 'dmsp_val',
 'dryy_hgpr_date',
 'dryy_hgpr_vrss_prpr_rate',
 'dryy_lwpr_date',
 'dryy_lwpr_vrss_prpr_rate',
 'elw_pblc_yn',
 'eps',
 'fcam_cnnm',
 'frgn_hldn_qty',
 'frgn_ntby_qty',
 'grmn_rate_cls_code',
 'hts_avls',
 'hts_deal_qty_unit_val',
 'hts_frgn_ehrt',
 'invt_caful_yn',
 'iscd_stat_cls_code',
 'last_ssts_cntg_qty',
 'lstn_stcn',
 'mang_issu_cls_code',
 'marg_rate',
 'mrkt_warn_cls_code',
 'oprc_rang_cont_yn',
 'ovtm_vi_cls_code',
 'pbr',
 'per',
 'pgtr_ntby_qty',
 'prdy_ctrt',
 'prdy_vrss',
 'prdy_vrss_sign',
 'prdy_vrss_vol_rate',
 'pvt_frst_dmrs_prc',
 'pvt_frst_dmsp_prc',
 'pvt_pont_val',
 'pvt_scnd_dmrs_prc',
 'pvt_scnd_dmsp_prc',
 'rprs_mrkt_kor_name',
 'rstc_wdth_prc',
 'short_over_yn',
 'sltr_yn',
 'ssts_yn',
 'stac_month',
 'stck_dryy_hgpr',
 'stck_dryy_lwpr',
 'stck_fcam',
 'stck_hgpr',
 'stck_llam',
 'stck_lwpr',
 'stck_mxpr',
 'stck_oprc',
 'stck_prpr',
 'stck_sdpr',
 'stck_shrn_iscd',
 'stck_sspr',
 'temp_stop_yn',
 'vi_cls_code',
 'vol_tnrt',
 'w52_hgpr',
 'w52_hgpr_date',
 'w52_hgpr_vrss_prpr_ctrt',
 'w52_lwpr',
 'w52_lwpr_date',
 'w52_lwpr_vrss_prpr_ctrt',
 'wghn_avrg_stck_prc',
 'whol_loan_rmnd_rate']

In [ ]:
pprint.pprint(resp['output'])

{'acml_tr_pbmn': '1136775319150',
 'acml_vol': '11490316',
 'aspr_unit': '100',
 'bps': '57930.00',
 'bstp_kor_isnm': '전기·전자',
 'clpr_rang_cont_yn': 'N',
 'cpfn': '7780',
 'cpfn_cnnm': '7,780 억',
 'crdt_able_yn': 'Y',
 'd250_hgpr': '112400',
 'd250_hgpr_date': '20251104',
 'd250_hgpr_vrss_prpr_rate': '-11.92',
 'd250_lwpr': '49900',
 'd250_lwpr_date': '20241114',
 'd250_lwpr_vrss_prpr_rate': '98.40',
 'dmrs_val': '104450',
 'dmsp_val': '102550',
 'dryy_hgpr_date': '20251104',
 'dryy_hgpr_vrss_prpr_rate': '-11.92',
 'dryy_lwpr_date': '20250203',
 'dryy_lwpr_vrss_prpr_rate': '94.88',
 'elw_pblc_yn': 'Y',
 'eps': '4950.00',
 'fcam_cnnm': '100',
 'frgn_hldn_qty': '3098479227',
 'frgn_ntby_qty': '0',
 'grmn_rate_cls_code': '40',
 'hts_avls': '5860442',
 'hts_deal_qty_unit_val': '1',
 'hts_frgn_ehrt': '52.34',
 'invt_caful_yn': 'N',
 'iscd_stat_cls_code': '55',
 'last_ssts_cntg_qty': '1004180',
 'lstn_stcn': '5919637922',
 'mang_issu_cls_code': 'N',
 'marg_rate': '20.00',
 'mrkt_warn_cls_code': '00',
 'oprc_rang_cont_yn': 'N',
 'ovtm_vi_cls_code': 'N',
 'pbr': '1.71',
 'per': '20.00',
 'pgtr_ntby_qty': '-3079806',
 'prdy_ctrt': '-3.70',
 'prdy_vrss': '-3800',
 'prdy_vrss_sign': '5',
 'prdy_vrss_vol_rate': '55.14',
 'pvt_frst_dmrs_prc': '103900',
 'pvt_frst_dmsp_prc': '102000',
 'pvt_pont_val': '103100',
 'pvt_scnd_dmrs_prc': '105000',
 'pvt_scnd_dmsp_prc': '101200',
 'rprs_mrkt_kor_name': 'KOSPI200',
 'rstc_wdth_prc': '30800',
 'short_over_yn': 'N',
 'sltr_yn': 'N',
 'ssts_yn': 'Y',
 'stac_month': '12',
 'stck_dryy_hgpr': '112400',
 'stck_dryy_lwpr': '50800',
 'stck_fcam': '100',
 'stck_hgpr': '99600',
 'stck_llam': '72000',
 'stck_lwpr': '98500',
 'stck_mxpr': '133600',
 'stck_oprc': '99000',
 'stck_prpr': '99000',
 'stck_sdpr': '102800',
 'stck_shrn_iscd': '005930',
 'stck_sspr': '78120',
 'temp_stop_yn': 'N',
 'vi_cls_code': 'N',
 'vol_tnrt': '0.19',
 'w52_hgpr': '112400',
 'w52_hgpr_date': '20251104',
 'w52_hgpr_vrss_prpr_ctrt': '-11.92',
 'w52_lwpr': '49900',
 'w52_lwpr_date': '20241114',
 'w52_lwpr_vrss_prpr_ctrt': '98.40',
 'wghn_avrg_stck_prc': '98933.21',
 'whol_loan_rmnd_rate': '0.27'}

In [ ]:
param_explain = {
    'acml_tr_pbmn': '누적 거래대금',
    'acml_vol': '누적 거래량',
    'aspr_unit': '호가단위',
    'bps': '주당순자산(BPS)',
    'bstp_kor_isnm': '업종 한글명',
    'clpr_rang_cont_yn': '종가범위제한여부',
    'cpfn': '자본금',
    'cpfn_cnnm': '자본금 단위명',
    'crdt_able_yn': '신용거래가능여부',
    'd250_hgpr': '250일 최고가',
    'd250_hgpr_date': '250일 최고가일',
    'd250_hgpr_vrss_prpr_rate': '250일 고가 대비 현재가 등락률',
    'd250_lwpr': '250일 최저가',
    'd250_lwpr_date': '250일 최저가일',
    'd250_lwpr_vrss_prpr_rate': '250일 저가 대비 현재가 등락률',
    'dmrs_val': '변동성완화 발동가',
    'dmsp_val': '변동성완화 해제발동가',
    'dryy_hgpr_date': '작년 고가일',
    'dryy_hgpr_vrss_prpr_rate': '작년 고가 대비 현재가 등락률',
    'dryy_lwpr_date': '작년 저가일',
    'dryy_lwpr_vrss_prpr_rate': '작년 저가 대비 현재가 등락률',
    'elw_pblc_yn': 'ELW 발행 여부',
    'eps': '주당순이익(EPS)',
    'fcam_cnnm': '액면가 단위명',
    'frgn_hldn_qty': '외국인 보유수량',
    'frgn_ntby_qty': '외인 순매수량',
    'grmn_rate_cls_code': '보증금비율분류코드',
    'hts_avls': 'HTS 시가총액',
    'hts_deal_qty_unit_val': 'HTS 거래수량 단위',
    'hts_frgn_ehrt': 'HTS 외인 지분율',
    'invt_caful_yn': '투자주의 여부',
    'iscd_stat_cls_code': '종목 상태 분류코드',
    'last_ssts_cntg_qty': '최종 단일가 체결수량',
    'lstn_stcn': '상장주식수',
    'mang_issu_cls_code': '관리종목 분류코드',
    'marg_rate': '증거금 비율',
    'mrkt_warn_cls_code': '시장경고 분류코드',
    'oprc_rang_cont_yn': '시가범위제한여부',
    'ovtm_vi_cls_code': '시간외 VI 분류코드',
    'pbr': '주가순자산비율(PBR)',
    'per': '주가수익비율(PER)',
    'pgtr_ntby_qty': '프로그램 순매수량',
    'prdy_ctrt': '전일 대비 등락률(%)',
    'prdy_vrss': '전일 대비',
    'prdy_vrss_sign': '전일 대비 부호',
    'prdy_vrss_vol_rate': '전일 대비 거래량 비율',
    'pvt_frst_dmrs_prc': '예비 1차 변동성완화발동가',
    'pvt_frst_dmsp_prc': '예비 1차 변동성완화해제발동가',
    'pvt_pont_val': '변동성완화 발동 기준값',
    'pvt_scnd_dmrs_prc': '예비 2차 변동성완화발동가',
    'pvt_scnd_dmsp_prc': '예비 2차 변동성완화해제발동가',
    'rstc_wdth_prc': '제한폭',
    'short_over_yn': '공매도 과열종목 여부',
    'sltr_yn': '정리매매여부',
    'ssts_yn': '서스펜션여부',
    'stac_month': '결산월',
    'stck_dryy_hgpr': '작년(연) 최고가',
    'stck_dryy_lwpr': '작년(연) 최저가',
    'stck_fcam': '액면가',
    'stck_hgpr': '고가',
    'stck_llam': '하한가',
    'stck_lwpr': '저가',
    'stck_mxpr': '상한가',
    'stck_oprc': '시가',
    'stck_prpr': '현재가',
    'stck_sdpr': '기준가',
    'stck_shrn_iscd': '주식 단축코드',
    'stck_sspr': '주식초가',
    'temp_stop_yn': '임시정지여부',
    'vi_cls_code': 'VI(변동성완화장치) 분류코드',
    'vol_tnrt': '거래량회전율',
    'w52_hgpr': '52주 최고가',
    'w52_hgpr_date': '52주 최고가일',
    'w52_hgpr_vrss_prpr_ctrt': '52주 고가 대비 현재가 등락률',
    'w52_lwpr': '52주 최저가',
    'w52_lwpr_date': '52주 최저가일',
    'w52_lwpr_vrss_prpr_ctrt': '52주 저가 대비 현재가 등락률',
    'wghn_avrg_stck_prc': '가중평균주가',
    'whol_loan_rmnd_rate': '전체 융자잔액율'
}

pprint.pprint(param_explain)

{'acml_tr_pbmn': '누적 거래대금',
 'acml_vol': '누적 거래량',
 'aspr_unit': '호가단위',
 'bps': '주당순자산(BPS)',
 'bstp_kor_isnm': '업종 한글명',
 'clpr_rang_cont_yn': '종가범위제한여부',
 'cpfn': '자본금',
 'cpfn_cnnm': '자본금 단위명',
 'crdt_able_yn': '신용거래가능여부',
 'd250_hgpr': '250일 최고가',
 'd250_hgpr_date': '250일 최고가일',
 'd250_hgpr_vrss_prpr_rate': '250일 고가 대비 현재가 등락률',
 'd250_lwpr': '250일 최저가',
 'd250_lwpr_date': '250일 최저가일',
 'd250_lwpr_vrss_prpr_rate': '250일 저가 대비 현재가 등락률',
 'dmrs_val': '변동성완화 발동가',
 'dmsp_val': '변동성완화 해제발동가',
 'dryy_hgpr_date': '작년 고가일',
 'dryy_hgpr_vrss_prpr_rate': '작년 고가 대비 현재가 등락률',
 'dryy_lwpr_date': '작년 저가일',
 'dryy_lwpr_vrss_prpr_rate': '작년 저가 대비 현재가 등락률',
 'elw_pblc_yn': 'ELW 발행 여부',
 'eps': '주당순이익(EPS)',
 'fcam_cnnm': '액면가 단위명',
 'frgn_hldn_qty': '외국인 보유수량',
 'frgn_ntby_qty': '외인 순매수량',
 'grmn_rate_cls_code': '보증금비율분류코드',
 'hts_avls': 'HTS 시가총액',
 'hts_deal_qty_unit_val': 'HTS 거래수량 단위',
 'hts_frgn_ehrt': 'HTS 외인 지분율',
 'invt_caful_yn': '투자주의 여부',
 'iscd_stat_cls_code': '종목 상태 분류코드',
 'last_ssts_cntg_qty': '최종 단일가 체결수량',
 'lstn_stcn': '상장주식수',
 'mang_issu_cls_code': '관리종목 분류코드',
 'marg_rate': '증거금 비율',
 'mrkt_warn_cls_code': '시장경고 분류코드',
 'oprc_rang_cont_yn': '시가범위제한여부',
 'ovtm_vi_cls_code': '시간외 VI 분류코드',
 'pbr': '주가순자산비율(PBR)',
 'per': '주가수익비율(PER)',
 'pgtr_ntby_qty': '프로그램 순매수량',
 'prdy_ctrt': '전일 대비 등락률(%)',
 'prdy_vrss': '전일 대비',
 'prdy_vrss_sign': '전일 대비 부호',
 'prdy_vrss_vol_rate': '전일 대비 거래량 비율',
 'pvt_frst_dmrs_prc': '예비 1차 변동성완화발동가',
 'pvt_frst_dmsp_prc': '예비 1차 변동성완화해제발동가',
 'pvt_pont_val': '변동성완화 발동 기준값',
 'pvt_scnd_dmrs_prc': '예비 2차 변동성완화발동가',
 'pvt_scnd_dmsp_prc': '예비 2차 변동성완화해제발동가',
 'rstc_wdth_prc': '제한폭',
 'short_over_yn': '공매도 과열종목 여부',
 'sltr_yn': '정리매매여부',
 'ssts_yn': '서스펜션여부',
 'stac_month': '결산월',
 'stck_dryy_hgpr': '작년(연) 최고가',
 'stck_dryy_lwpr': '작년(연) 최저가',
 'stck_fcam': '액면가',
 'stck_hgpr': '고가',
 'stck_llam': '하한가',
 'stck_lwpr': '저가',
 'stck_mxpr': '상한가',
 'stck_oprc': '시가',
 'stck_prpr': '현재가',
 'stck_sdpr': '기준가',
 'stck_shrn_iscd': '주식 단축코드',
 'stck_sspr': '주식초가',
 'temp_stop_yn': '임시정지여부',
 'vi_cls_code': 'VI(변동성완화장치) 분류코드',
 'vol_tnrt': '거래량회전율',
 'w52_hgpr': '52주 최고가',
 'w52_hgpr_date': '52주 최고가일',
 'w52_hgpr_vrss_prpr_ctrt': '52주 고가 대비 현재가 등락률',
 'w52_lwpr': '52주 최저가',
 'w52_lwpr_date': '52주 최저가일',
 'w52_lwpr_vrss_prpr_ctrt': '52주 저가 대비 현재가 등락률',
 'wghn_avrg_stck_prc': '가중평균주가',
 'whol_loan_rmnd_rate': '전체 융자잔액율'}

In [ ]:
dir(broker)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_fetch_today_1m_ohlcv',
 'acc_no',
 'acc_no_postfix',
 'acc_no_prefix',
 'access_token',
 'api_key',
 'api_secret',
 'base_url',
 'cancel_order',
 'check_access_token',
 'check_buy_order',
 'create_limit_buy_order',
 'create_limit_sell_order',
 'create_market_buy_order',
 'create_market_sell_order',
 'create_order',
 'create_oversea_order',
 'download_master_file',
 'exchange',
 'fetch_balance',
 'fetch_balance_domestic',
 'fetch_balance_oversea',
 'fetch_domestic_price',
 'fetch_kosdaq_symbols',
 'fetch_kospi_symbols',
 'fetch_ohlcv',
 'fetch_ohlcv_domestic',
 'fetch_ohlcv_overesea',
 'fetch_ohlcv_recent30',
 'fetch_open_order',
 'fetch_oversea_day_night',
 'fetch_oversea_price',
 'fetch_present_balance',
 'fetch_price',
 'fetch_symbols',
 'fetch_today_1m_ohlcv',
 'issue_access_token',
 'issue_hashkey',
 'load_access_token',
 'mock',
 'modify_order',
 'parse_kosdaq_master',
 'parse_kospi_master',
 'set_base_url',
 'update_order']

In [ ]:
symbols = broker.fetch_symbols()
symbols

           단축코드              한글명 그룹코드   시장
0     F70100022     한투미국경제주도1(A)   BC  코스피
1     F70100023   한투미국경제주도1(A-e)   BC  코스피
2     F70100024     한투미국경제주도2(A)   BC  코스피
3     F70100025   한투미국경제주도2(A-e)   BC  코스피
4     F70100026  한투글로벌넥스트웨이브1(A)   BC  코스피
...         ...              ...  ...  ...
1800     950200              소마젠   DR  코스닥
1801     900120            씨엑스아이   FS  코스닥
1802     900250          크리스탈신소재   FS  코스닥
1803     900070           글로벌에스엠   FS  코스닥
1804     900100             애머릿지   FS  코스닥

[4282 rows x 4 columns]

In [ ]:
resp = broker.fetch_balance()
resp

{'output1': [{'pdno': '092200',
   'prdt_name': '디아이씨',
   'trad_dvsn_name': '현금',
   'bfdy_buy_qty': '0',
   'bfdy_sll_qty': '0',
   'thdt_buyqty': '1',
   'thdt_sll_qty': '1',
   'hldg_qty': '0',
   'ord_psbl_qty': '0',
   'pchs_avg_pric': '0.0000',
   'pchs_amt': '0',
   'prpr': '5690',
   'evlu_amt': '0',
   'evlu_pfls_amt': '0',
   'evlu_pfls_rt': '0.00',
   'evlu_erng_rt': '0.00000000',
   'loan_dt': '',
   'loan_amt': '0',
   'stln_slng_chgs': '0',
   'expd_dt': '',
   'fltt_rt': '-7.47967480',
   'bfdy_cprs_icdc': '-460',
   'item_mgna_rt_name': '60%',
   'grta_rt_name': '45%',
   'sbst_pric': '4550',
   'stck_loan_unpr': '0.0000'}],
 'output2': [{'dnca_tot_amt': '50000',
   'nxdy_excc_amt': '50000',
   'prvs_rcdl_excc_amt': '49962',
   'cma_evlu_amt': '0',
   'bfdy_buy_amt': '0',
   'thdt_buy_amt': '5920',
   'nxdy_auto_rdpt_amt': '0',
   'bfdy_sll_amt': '0',
   'thdt_sll_amt': '5890',
   'd2_auto_rdpt_amt': '0',
   'bfdy_tlex_amt': '0',
   'thdt_tlex_amt': '8',
   'tot_loan_amt': '0',
   'scts_evlu_amt': '0',
   'tot_evlu_amt': '49962',
   'nass_amt': '49962',
   'fncg_gld_auto_rdpt_yn': '',
   'pchs_amt_smtl_amt': '0',
   'evlu_amt_smtl_amt': '0',
   'evlu_pfls_smtl_amt': '0',
   'tot_stln_slng_chgs': '0',
   'bfdy_tot_asst_evlu_amt': '50000',
   'asst_icdc_amt': '-38',
   'asst_icdc_erng_rt': '0.00000000'}]}

종가, 고가, 저가, 시가, 거래량 반환

In [ ]:
# 지정한 종목코드의 과거 ~ 오늘까지 날짜별 시세 (종가, 고가, 저가, 시가, 거래량)를 DataFrame으로 반환
import pandas as pd
from datetime import datetime

def get_daily_price_df(code: str = "005930") -> pd.DataFrame:
    """
    주어진 종목 코드의 오늘까지(최신 포함) 일자별 시세를 DataFrame으로 반환합니다.
    DataFrame 컬럼: ['date', 'close', 'high', 'low', 'open', 'volume']

    Args:
        code (str): 조회할 종목의 코드. 6자리 숫자 문자열.

    Returns:
        pd.DataFrame: 날짜 기준으로 정렬된 시세 데이터프레임.  
            col = ['date','close','high','low','open','volume']
            date: YYYYMMDD(문자열)
    """
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급 실패")

    PATH = "uapi/domestic-stock/v1/quotations/inquire-daily-price"
    URL = f"{URL_BASE}/{PATH}"

    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010400",  # 일자별 시세조회
    }
    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": code,
        "fid_org_adj_prc": "1",
        "fid_period_div_code": "D",
    }

    res = requests.get(URL, headers=headers, params=params, timeout=10)
    if res.status_code != 200:
        print("API 호출 실패")
        print("res.status_code: ", res.status_code)
        return None

    data = res.json()
    rows = data.get("output", []) or []
    if not rows:
        return None

    # 원하는 컬럼: 날짜, 종가, 고가, 저가, 시가, 거래량
    records = []
    for row in rows:
        records.append({
            'Date': row.get('stck_bsop_date'),   # YYYYMMDD
            'Close': int(row.get('stck_clpr', '0')),
            'High': int(row.get('stck_hgpr', '0')),
            'Low': int(row.get('stck_lwpr', '0')),
            'Open': int(row.get('stck_oprc', '0')),
            'Volume': int(row.get('acml_vol', '0')),
        })
    # 날짜 내림차순이 보통이므로 오름차순 정렬
    df = pd.DataFrame(records)
    df = df.sort_values('Date').reset_index(drop=True)
    return df

# 사용 예시
df_price = get_daily_price_df("005930")
print(df_price)

{'content': '[2025-11-27 11:07:48] saved token loading'}
        Date   Close    High     Low    Open    Volume
0   20251017   97900   99100   96700   97200  22730809
1   20251020   98100   98300   96000   97900  17589756
2   20251021   97500   99900   97300   98500  22803830
3   20251022   98600   98600   95500   97100  15937611
4   20251023   96500   98500   96300   96800  18488581
5   20251024   98800   99000   97700   97900  18801925
6   20251027  102000  102000  100600  101300  22169970
7   20251028   99500  101000   99100  100900  20002282
8   20251029  100500  101000   99100  100200  20899788
9   20251030  104100  105800  102000  102400  34570017
10  20251031  107500  108600  103300  105000  54824564
11  20251103  111100  111500  106500  106900  30110066
12  20251104  104900  112400  104900  111800  30450281
13  20251105  100600  102000   96700  101000  44843020
14  20251106   99200  103800   98800  103700  28655689
15  20251107   97900  100300   96300   96400  22908083
16  20251110  100600  101000   97900   98600  23842327
17  20251111  103500  106000  102000  103700  27742542
18  20251112  103100  103900  101600  103000  19413497
19  20251113  102800  104200  102300  102500  20838741
20  20251114   97200   99600   97200   99000  21806342
21  20251117  100600  101000   99500   99800  17192584
22  20251118   97800  100900   97500   99800  18684068
23  20251119   96500   97500   94600   97100  18993346
24  20251120  100600  102900   99500  100900  25360435
25  20251121   94800   96800   94500   95600  23103574
26  20251124   96700   99000   96200   97800  29831172
27  20251125   99300  101400   97800  101400  16110054
28  20251126  102800  102900   99300  100500  21314975
29  20251127  104000  105500  103700  104100   9001121

In [ ]:
# 신호 출력 함수 생성

import pandas as pd
import yfinance as yf

# 1. 데이터 불러오기
df = get_daily_price_df()   # 종목 코드 입력
# print(df)
# 2. RSI, MACD 지표 계산 함수 정의
def compute_rsi(series, period=7):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=period, min_periods=period).mean()
    avg_loss = loss.rolling(window=period, min_periods=period).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def compute_macd(series, fast=8, slow=17, signal=5):
    """
    예시 조합 1: (5, 13, 3) → 빠른 반응, 스캘핑에 적합
    예시 조합 2: (8, 17, 5) → 약간의 안정성 확보, 데이 트레이딩에 적합
    """
    ema_fast = series.ewm(span=fast, adjust=False).mean()
    ema_slow = series.ewm(span=slow, adjust=False).mean()
    macd = ema_fast - ema_slow
    macd_signal = macd.ewm(span=signal, adjust=False).mean()
    return macd, macd_signal

# 3. 각 컬럼 생성
df['RSI_fast'] = compute_rsi(df['Close'], period = 7)
df['RSI_slow'] = compute_rsi(df['Close'], period = 25)
df['MACD'], df['Signal'] = compute_macd(df['Close'])

# 4. trading_signal 함수 수정 (iloc/lon으로 스칼라값만 비교하도록 에러 수정)
def trading_signal(df, rsi_fast_column='RSI_fast', rsi_slow_column='RSI_slow', macd_column='MACD', signal_column='Signal'):
    """
    df: DataFrame with 'RSI_fast', 'RSI_slow', 'MACD', 'Signal' columns
    return: pd.Series of 'Buy', 'Sell', or 'Hold'
    """
    signals = []
    for i in range(1, len(df)):
        # .iloc[]로 스칼라값 추출 → Series가 아닌 float/np.nan
        rsi_fast = df[rsi_fast_column].iloc[i]
        rsi_slow = df[rsi_slow_column].iloc[i]
        macd = df[macd_column].iloc[i]
        macd_prev = df[macd_column].iloc[i-1]
        signal = df[signal_column].iloc[i]
        signal_prev = df[signal_column].iloc[i-1]
        
        if pd.isna(rsi_fast) or pd.isna(rsi_slow) or pd.isna(macd) or pd.isna(macd_prev) or pd.isna(signal) or pd.isna(signal_prev):
            signals.append('Hold')
            continue

        # Buy condition
        if (rsi_fast < 30) and (macd > signal) and (macd_prev < signal_prev) and (rsi_fast > rsi_slow):
            signals.append('Buy')
        # Sell condition
        elif (rsi_fast > 70) and (macd < signal) and (macd_prev > signal_prev) and (rsi_fast < rsi_slow):
            signals.append('Sell')
        else:
            signals.append('Hold')
    signals = ['Hold'] + signals    # 첫 데이터는 비교 불가이므로 Hold
    return pd.Series(signals, index=df.index)

df['Trade_signal'] = trading_signal(df, 'RSI_fast', 'RSI_slow', 'MACD', 'Signal')
df

,Date,Close,High,Low,Open,Volume,RSI_fast,RSI_slow,MACD,Signal,Trade_signal
0,20251017,97900,99100,96700,97200,22730809,NaN,NaN,0.000000,0.000000,Hold
1,20251020,98100,98300,96000,97900,17589756,NaN,NaN,22.222222,7.407407,Hold
2,20251021,97500,99900,97300,98500,22803830,NaN,NaN,-29.629630,-4.938272,Hold
3,20251022,98600,98600,95500,97100,15937611,NaN,NaN,57.475995,15.866484,Hold
4,20251023,96500,98500,96300,96800,18488581,NaN,NaN,-117.055327,-28.440786,Hold
5,20251024,98800,99000,97700,97900,18801925,NaN,NaN,20.726854,-12.051573,Hold
6,20251027,102000,102000,100600,101300,22169970,NaN,NaN,471.027452,148.974769,Hold
7,20251028,99500,101000,99100,100900,20002282,56.666667,NaN,492.938298,263.629279,Hold
8,20251029,100500,101000,99100,100200,20899788,59.375000,NaN,607.026333,378.094963,Hold
9,20251030,104100,105800,102000,102400,34570017,70.886076,NaN,1070.913707,609.034545,Hold
10,20251031,107500,108600,103300,105000,54824564,74.585635,NaN,1742.961429,987.010173,Hold
11,20251103,111100,111500,106500,106900,30110066,87.244898,NaN,2564.550931,1512.857092,Hold
12,20251104,104900,112400,104900,111800,30450281,62.978723,NaN,2380.352291,1802.022158,Hold
13,20251105,100600,102000,96700,101000,44843020,47.154472,NaN,1716.453175,1773.499164,Hold
14,20251106,99200,103800,98800,103700,28655689,49.361702,NaN,1059.524078,1535.507469,Hold
15,20251107,97900,100300,96300,96400,22908083,44.537815,NaN,434.745343,1168.586760,Hold
16,20251110,100600,101000,97900,98600,23842327,42.358079,NaN,292.065098,876.412873,Hold
17,20251111,103500,106000,102000,103700,27742542,41.071429,NaN,508.432703,753.752816,Hold
18,20251112,103100,103900,101600,103000,19413497,29.166667,NaN,601.021845,702.842493,Hold
19,20251113,102800,104200,102300,102500,20838741,42.105263,NaN,616.860713,674.181899,Hold
20,20251114,97200,99600,97200,99000,21806342,38.356164,NaN,-9.642310,446.240496,Hold
21,20251117,100600,101000,99500,99800,17192584,54.216867,NaN,-64.764343,275.905550,Hold
22,20251118,97800,100900,97500,99800,18684068,49.723757,NaN,-412.385394,46.475235,Hold
23,20251119,96500,97500,94600,97100,18993346,37.724551,NaN,-786.978086,-231.342539,Hold
24,20251120,100600,102900,99500,100900,25360435,41.899441,NaN,-570.968637,-344.551238,Hold
25,20251121,94800,96800,94500,95600,23103574,32.188841,47.655068,-1051.975224,-580.359233,Hold
26,20251124,96700,99000,96200,97800,29831172,37.751004,48.967552,-1147.437180,-769.385216,Hold
27,20251125,99300,101400,97800,101400,16110054,54.794521,51.289398,-896.214898,-811.661776,Hold
28,20251126,102800,102900,99300,100500,21314975,55.000000,52.908587,-311.512706,-644.945420,Hold
29,20251127,104000,105500,103700,104100,9009924,65.196078,55.259467,233.750852,-352.046662,Hold

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_columns')
# pd.set_option('display.max_columns', 10)   # 10개의 컬럼만 보이게
# pd.set_option('display.max_rows', 20)      # 20개의 행만 보이게

In [ ]:
# 설계
import pandas as pd

trading_signal()
df = pd.DataFrame()

In [ ]:
# RSI, CDMA 활용한 수정
# df = pd.DataFrame()
def get_target_price(code="005930"):
    """매수 시그널 발생 시 해당 일의 종가를 매수가로 반환"""
    df['Trade_signal'] = trading_signal(df, 'RSI_fast', 'RSI_slow', 'MACD', 'Signal')
    buy_signals = df[df['Trade_signal'] == 'Buy']
    print(df)
    print(buy_signals)
    if buy_signals.empty:
        return None  # 매수 시그널이 없는 경우 None 반환
    # 매수 신호가 여러 번이면 첫번째 or 마지막 등 정책에 따라 변경 가능
    # 여기서는 가장 최근의(마지막) 매수 신호를 사용
    last_buy_signal = buy_signals.iloc[-1]
    target_price = last_buy_signal['Close']
    return target_price

print(get_target_price())

        Date   Close    High     Low    Open    Volume   RSI_fast   RSI_slow  \
0   20251017   97900   99100   96700   97200  22730809        NaN        NaN
1   20251020   98100   98300   96000   97900  17589756        NaN        NaN
2   20251021   97500   99900   97300   98500  22803830        NaN        NaN
3   20251022   98600   98600   95500   97100  15937611        NaN        NaN
4   20251023   96500   98500   96300   96800  18488581        NaN        NaN
5   20251024   98800   99000   97700   97900  18801925        NaN        NaN
6   20251027  102000  102000  100600  101300  22169970        NaN        NaN
7   20251028   99500  101000   99100  100900  20002282  56.666667        NaN
8   20251029  100500  101000   99100  100200  20899788  59.375000        NaN
9   20251030  104100  105800  102000  102400  34570017  70.886076        NaN
10  20251031  107500  108600  103300  105000  54824564  74.585635        NaN
11  20251103  111100  111500  106500  106900  30110066  87.244898        NaN
12  20251104  104900  112400  104900  111800  30450281  62.978723        NaN
13  20251105  100600  102000   96700  101000  44843020  47.154472        NaN
14  20251106   99200  103800   98800  103700  28655689  49.361702        NaN
15  20251107   97900  100300   96300   96400  22908083  44.537815        NaN
16  20251110  100600  101000   97900   98600  23842327  42.358079        NaN
17  20251111  103500  106000  102000  103700  27742542  41.071429        NaN
18  20251112  103100  103900  101600  103000  19413497  29.166667        NaN
19  20251113  102800  104200  102300  102500  20838741  42.105263        NaN
20  20251114   97200   99600   97200   99000  21806342  38.356164        NaN
21  20251117  100600  101000   99500   99800  17192584  54.216867        NaN
22  20251118   97800  100900   97500   99800  18684068  49.723757        NaN
23  20251119   96500   97500   94600   97100  18993346  37.724551        NaN
24  20251120  100600  102900   99500  100900  25360435  41.899441        NaN
25  20251121   94800   96800   94500   95600  23103574  32.188841  47.655068
26  20251124   96700   99000   96200   97800  29831172  37.751004  48.967552
27  20251125   99300  101400   97800  101400  16110054  54.794521  51.289398
28  20251126  102800  102900   99300  100500  21314975  55.000000  52.908587
29  20251127  104000  105500  103700  104100   9009924  65.196078  55.259467

           MACD       Signal Trade_signal
0      0.000000     0.000000         Hold
1     22.222222     7.407407         Hold
2    -29.629630    -4.938272         Hold
3     57.475995    15.866484         Hold
4   -117.055327   -28.440786         Hold
5     20.726854   -12.051573         Hold
6    471.027452   148.974769         Hold
7    492.938298   263.629279         Hold
8    607.026333   378.094963         Hold
9   1070.913707   609.034545         Hold
10  1742.961429   987.010173         Hold
11  2564.550931  1512.857092         Hold
12  2380.352291  1802.022158         Hold
13  1716.453175  1773.499164         Hold
14  1059.524078  1535.507469         Hold
15   434.745343  1168.586760         Hold
16   292.065098   876.412873         Hold
17   508.432703   753.752816         Hold
18   601.021845   702.842493         Hold
19   616.860713   674.181899         Hold
20    -9.642310   446.240496         Hold
21   -64.764343   275.905550         Hold
22  -412.385394    46.475235         Hold
23  -786.978086  -231.342539         Hold
24  -570.968637  -344.551238         Hold
25 -1051.975224  -580.359233         Hold
26 -1147.437180  -769.385216         Hold
27  -896.214898  -811.661776         Hold
28  -311.512706  -644.945420         Hold
29   233.750852  -352.046662         Hold
        Date   Close    High     Low    Open    Volume   RSI_fast   RSI_slow  \
0   20251017   97900   99100   96700   97200  22730809        NaN        NaN
1   20251020   98100   98300   96000   97900  17589756        NaN        NaN
2   20251021   97500   99900   97300   98500  22803830        NaN        NaN
3   20251022   98600   98600   95500   97100  15937611        NaN        NaN
4   20251023   96500   98500   96300   96800  18488581        NaN        NaN
5   20251024   98800   99000   97700   97900  18801925        NaN        NaN
6   20251027  102000  102000  100600  101300  22169970        NaN        NaN
7   20251028   99500  101000   99100  100900  20002282  56.666667        NaN
8   20251029  100500  101000   99100  100200  20899788  59.375000        NaN
9   20251030  104100  105800  102000  102400  34570017  70.886076        NaN
10  20251031  107500  108600  103300  105000  54824564  74.585635        NaN
11  20251103  111100  111500  106500  106900  30110066  87.244898        NaN
12  20251104  104900  112400  104900  111800  30450281  62.978723        NaN
13  20251105  100600  102000   96700  101000  44843020  47.154472        NaN
14  20251106   99200  103800   98800  103700  28655689  49.361702        NaN
15  20251107   97900  100300   96300   96400  22908083  44.537815        NaN
16  20251110  100600  101000   97900   98600  23842327  42.358079        NaN
17  20251111  103500  106000  102000  103700  27742542  41.071429        NaN
18  20251112  103100  103900  101600  103000  19413497  29.166667        NaN
19  20251113  102800  104200  102300  102500  20838741  42.105263        NaN
20  20251114   97200   99600   97200   99000  21806342  38.356164        NaN
21  20251117  100600  101000   99500   99800  17192584  54.216867        NaN
22  20251118   97800  100900   97500   99800  18684068  49.723757        NaN
23  20251119   96500   97500   94600   97100  18993346  37.724551        NaN
24  20251120  100600  102900   99500  100900  25360435  41.899441        NaN
25  20251121   94800   96800   94500   95600  23103574  32.188841  47.655068
26  20251124   96700   99000   96200   97800  29831172  37.751004  48.967552
27  20251125   99300  101400   97800  101400  16110054  54.794521  51.289398
28  20251126  102800  102900   99300  100500  21314975  55.000000  52.908587
29  20251127  104000  105500  103700  104100   9009924  65.196078  55.259467

           MACD       Signal Trade_signal
0      0.000000     0.000000         Hold
1     22.222222     7.407407         Hold
2    -29.629630    -4.938272         Hold
3     57.475995    15.866484         Hold
4   -117.055327   -28.440786         Hold
5     20.726854   -12.051573         Hold
6    471.027452   148.974769         Hold
7    492.938298   263.629279         Hold
8    607.026333   378.094963         Hold
9   1070.913707   609.034545         Hold
10  1742.961429   987.010173         Hold
11  2564.550931  1512.857092         Hold
12  2380.352291  1802.022158         Hold
13  1716.453175  1773.499164         Hold
14  1059.524078  1535.507469         Hold
15   434.745343  1168.586760         Hold
16   292.065098   876.412873         Hold
17   508.432703   753.752816         Hold
18   601.021845   702.842493         Hold
19   616.860713   674.181899         Hold
20    -9.642310   446.240496         Hold
21   -64.764343   275.905550         Hold
22  -412.385394    46.475235         Hold
23  -786.978086  -231.342539         Hold
24  -570.968637  -344.551238         Hold
25 -1051.975224  -580.359233         Hold
26 -1147.437180  -769.385216         Hold
27  -896.214898  -811.661776         Hold
28  -311.512706  -644.945420         Hold
29   233.750852  -352.046662         Hold
104000

# 최종 코드

In [6]:
import json
import os
import sys
import traceback
from datetime import datetime
import time
import yaml
import requests
import shutil
import pandas as pd

# yaml 파일 로딩
with open('config.yaml', encoding='UTF-8') as f:
    _cfg = yaml.load(f, Loader=yaml.FullLoader)
APP_KEY = _cfg['APP_KEY']
APP_SECRET = _cfg['APP_SECRET']
ACCESS_TOKEN = ""
CANO = _cfg['CANO']
ACNT_PRDT_CD = _cfg['ACNT_PRDT_CD']
DISCORD_WEBHOOK_URL = _cfg['DISCORD_WEBHOOK_URL']
URL_BASE = _cfg['URL_BASE']

# 디스코드에 메시지 전송 함수
def send_message(msg):
    """
    디스코드 메세지를 전송합니다.
    msg: 전송할 메시지(문자열)
    """
    now = datetime.now()
    message = {"content": f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] {str(msg)}"}
    try:
        requests.post(DISCORD_WEBHOOK_URL, data=message)
    except Exception as e:
        print(f"디스코드 전송 에러: {e}")
    print(message)

# 토큰 파일 경로 설정
config_root = os.path.join(os.path.expanduser("~"), "workspace", "mini_project")
token_tmp = os.path.join(config_root, f"KIS{datetime.today().strftime('%Y%m%d')}")

# 접근토큰 관리하는 파일 존재여부 체크, 없으면 생성
if not os.path.exists(token_tmp):
    with open(token_tmp, "w+"):
        pass

# 토큰 저장
def save_token(my_token, my_expired):   
    """
    발급받은 토큰과 만료일시를 파일로 저장합니다.
    my_token: 토큰 문자열
    my_expired: 만료일시 (문자열, "%Y-%m-%d %H:%M:%S" 형식)
    """
    valid_date = datetime.strptime(my_expired, "%Y-%m-%d %H:%M:%S")
    with open(token_tmp, "w", encoding="utf-8") as f:
        f.write(f"token: {my_token}\n")
        f.write(f"valid-date: {valid_date}\n")
    send_message(f"token file name [{token_tmp}] stored")

# 예전 토큰 파일 expired 폴더로 이동
def move_old_tokens_to_expired():
    """
    오늘 이전 날짜의 모든 KIS 토큰 파일을 expired 폴더로 이동시킵니다.
    """
    try:
        expired_dir = os.path.join(config_root, "expired")
        if not os.path.exists(expired_dir):
            os.makedirs(expired_dir)
        today = datetime.today().date()
        # config_root 하위의 모든 토큰 파일을 순회
        for fname in os.listdir(config_root):
            if fname.startswith("KIS") and fname[3:11].isdigit():
                token_date_str = fname[3:11]
                try:
                    token_date = datetime.strptime(token_date_str, "%Y%m%d").date()
                except Exception:
                    continue  # 파일명이 날짜 형식에 맞지 않으면 스킵

                if token_date < today:
                    token_file_path = os.path.join(config_root, fname)
                    # 파일명에 타임스탬프 추가하여 이동 (중복 방지)
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    expired_file_path = os.path.join(expired_dir, f"{timestamp}_{fname}")
                    try:
                        shutil.move(token_file_path, expired_file_path)
                        send_message(f"오늘 이전({token_date})에 발급된 토큰 파일을 {expired_file_path}로 이동했습니다.")
                    except Exception as e:
                        send_message(f"{fname} 파일 이동 중 오류: {str(e)}")
    except Exception as e:
        send_message(f"만료된 토큰 파일 이동 작업 전체에서 오류 발생: {str(e)}")

# 토큰 불러오기 (만료체크)
def read_token():
    """
    저장된 토큰이 있으면 파일에서 읽어서 유효하면 반환,
    만료되었으면 None 반환 및 만료된 토큰 파일 expired로 이동
    """
    try:
        # yaml로 파싱 불안정하므로 직접 파싱
        token = None
        valid_date = None
        with open(token_tmp, encoding="UTF-8") as f:
            for line in f:
                if "token:" in line:
                    token = line.split(":",1)[1].strip()
                elif "valid-date:" in line:
                    valid_date_str = line.split(":",1)[1].strip()
                    valid_date = datetime.strptime(valid_date_str, "%Y-%m-%d %H:%M:%S")
        if token and valid_date:
            now = datetime.now()
            if valid_date > now:
                return token
            else:
                send_message("token expired")
                move_old_tokens_to_expired()
                return None
        return None
    except Exception:
        return None

# 토큰 발급 (저장된 토큰 있으면 재사용)
def get_access_token():
    """
    저장된 토큰 파일에서 유효한 토큰을 반환, 없거나 만료된 경우 새로 발급 후 저장 및 반환
    """
    global ACCESS_TOKEN
    saved_token = read_token()
    if saved_token is not None:
        send_message(f"saved token loading")
        ACCESS_TOKEN = saved_token
        move_old_tokens_to_expired()
        return saved_token
    headers = {"content-type": "application/json"}
    body = {
        "grant_type": "client_credentials",
        "appkey": APP_KEY,
        "appsecret": APP_SECRET
    }
    PATH = "oauth2/tokenP"
    URL = f"{URL_BASE}/{PATH}"
    res = requests.post(URL, headers=headers, data=json.dumps(body))
    if res.status_code == 200:
        ACCESS_TOKEN = res.json()["access_token"]
        my_expired = res.json()["access_token_token_expired"]
        save_token(ACCESS_TOKEN, my_expired)
        return ACCESS_TOKEN
    else:
        send_message(f"")
        print("토큰 발급 실패!")
        return None

# 주식 잔고 조회
def get_stock_balance():
    """
    주식 계좌의 보유 주식 종목과 수량을 조회하여 반환합니다.
    반환값: {종목코드(str): 보유수량(int)}
    """
    global ACCESS_TOKEN
    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-balance"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8434R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "",
        "INQR_DVSN": "02",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": "",
        "CTX_AREA_NK100": "",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output1" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[주식 잔고조회 실패] {msg}")
        raise ValueError(f"주식 잔고 조회 실패: {msg}")

    stock_list = data["output1"]
    evaluation = data.get("output2", [])
    stock_dict = {} # dict[str, int]
    # send_message("====주식 보유잔고====")
    
    for stock in stock_list:
        try:
            qty = int(stock.get("hldg_qty", "0"))
        except (TypeError, ValueError):
            qty = 0
        if qty > 0:
            pdno = stock.get("pdno", "")
            stock_dict[pdno] = qty
            # send_message(f"{stock.get('prdt_name', '미상')}({pdno}): {qty}주")
            # time.sleep(0.1)

    if evaluation:
        eval0 = evaluation[0]
        # send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
        # time.sleep(0.1)
        # send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
        # time.sleep(0.1)
        # send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
        # time.sleep(0.1)
    # send_message("=====================")

    return stock_dict, eval0


def print_stock_balance(stock_dict, eval0):
    
    send_message("==== 주식 보유잔고 ====")
    for pdno in stock_dict:    
        send_message(f"{symbol_dict[pdno]}({pdno}): {stock_dict[pdno]}주")
        time.sleep(0.1)
    send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
    time.sleep(0.1)
    send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
    time.sleep(0.1)
    send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
    time.sleep(0.1)
    send_message("=====================")
    return


# 현금 잔고 조회
def get_balance(price_code="005930", order_price="65500"):
    """
    계좌의 주문 가능 현금 잔고를 integer로 반환합니다.
    price_code: 조회할 종목코드(기본 005930), order_price: 가격(기본 65500)
    """
    
    global ACCESS_TOKEN
    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-psbl-order"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8908R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": price_code,
        "ORD_UNPR": order_price,
        "ORD_DVSN": "01",
        "CMA_EVLU_AMT_ICLD_YN": "Y",
        "OVRS_ICLD_YN": "Y",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[현금 잔고조회 실패] {msg}")
        raise ValueError(f"현금 잔고 조회 실패: {msg}")

    cash = int(data["output"]["ord_psbl_cash"])
    send_message(f"주문 가능 현금 잔고: {cash:,}원")
    return cash



# 현재가 조회
def get_current_price(stock_no="005930"):
    """
    입력한 종목의 현재가를 조회 후 문자열(가격)로 반환합니다.
    stock_no: 종목코드(문자열)
    """
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")
    
    PATH = "uapi/domestic-stock/v1/quotations/inquire-price"
    URL = f"{URL_BASE}/{PATH}"

    # 헤더 설정
    headers = {
        "Content-Type": "application/json", 
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010100"
    }

    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": stock_no
    }

    # 호출
    res = requests.get(URL, headers=headers, params=params)
    try:
        if res.status_code == 200 and res.json()["rt_cd"] == "0":
            return res.json()['output']['stck_prpr']
    except Exception:
        pass
    print("Error Code : " + str(res.status_code) + " | " + res.text)
    send_message(f"Error Code : {str(res.status_code)} | {res.text}")
    return None



####
####
# 전일 최고가, 최저가, 시가 조회
def get_prev_day_high_low(code="005930"):
    """
    주어진 종목의 전일(이전거래일) 날짜, 고가, 저가, 오늘시가 딕셔너리로 반환.
    code: 종목코드(문자열)
    반환값: dict 또는 None
    """
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급 실패")

    PATH = "uapi/domestic-stock/v1/quotations/inquire-daily-price"
    URL = f"{URL_BASE}/{PATH}"

    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010400",
    }
    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": code,
        "fid_org_adj_prc": "1",
        "fid_period_div_code": "D",
    }

    res = requests.get(URL, headers=headers, params=params, timeout=10)
    if res.status_code != 200:
        print("API 호출 실패")
        print("res.status_code: ", res.status_code)
        return None

    data = res.json()
    rows = data.get("output", []) or []
    if not rows:
        return None

    today_str = datetime.today().strftime("%Y%m%d")
    # 전일: 오늘보다 과거 날짜 중 가장 최근
    prev = None
    for row in rows:
        d = row.get("stck_bsop_date")
        if d and d < today_str:
            if prev is None or d > prev.get("stck_bsop_date"):
                prev = row
    if not prev:
        # 혹시 API가 오늘자 미포함으로 내려오는 경우, 관례적으로 rows[0]이 최근일, rows[1]이 전일
        if len(rows) > 1:
            prev = rows[1]
        else:
            return None

    return {
        "stck_bsop_date": prev.get("stck_bsop_date"),
        "prev_high": prev.get("stck_hgpr"),
        "prev_low": prev.get("stck_lwpr"),
        "stck_oprc": data['output'][0]['stck_oprc']
    }
    
    
# 목표가 지정
def get_target_price(code="005930"):
    """
    변동성 돌파전략: 오늘 시가 + (전일고가-전일저가)*0.5 = 목표가 반환
    code: 종목코드(문자열)
    반환값: float 또는 None (목표가)
    """
    prev_day_info = get_prev_day_high_low(code)
    if prev_day_info is None:
        send_message(f"{code} 목표가 조회 실패 (전일 정보 없음)")
        return None
    stck_oprc = int(prev_day_info['stck_oprc'])
    stck_hgpr = int(prev_day_info['prev_high'])
    stck_lwpr = int(prev_day_info['prev_low'])
    target_price = stck_oprc + (stck_hgpr - stck_lwpr) * 0.5
    return target_price

# 매수
def buy(code="005930", qty="1"):
    """
    특정 종목을 지정한 수량만큼 시장가로 매수. 성공시 True, 실패시 False 반환
    code: 종목코드, qty: 수량 (문자열 또는 정수)
    """
    global ACCESS_TOKEN
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": str(int(qty)),
        "ORD_UNPR": "0",
    }
    headers = {
        "Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0012U",    # (구)TTTC0802U → (신)TTTC0012U
        "custtype":"P",
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    try:
        if res.json()['rt_cd'] == '0':
            send_message(f"[매수 성공]{str(res.json())}")
            return True
        else:
            send_message(f"[매수 실패]{str(res.json())}")
            return False
    except Exception as ex:
        send_message(f"[매수 오류]{ex}")
        return False

# 매도
def sell(code="005930", qty="1"):
    """
    특정 종목을 지정한 수량만큼 시장가로 매도. 성공시 True, 실패시 False 반환
    code: 종목코드, qty: 수량 (문자열 또는 정수)
    """
    global ACCESS_TOKEN
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": qty,
        "ORD_UNPR": "0",
    }
    headers = {
        "Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0011U",    # (구)TTTC0801U → (신)TTTC0011U
        "custtype":"P",
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    try:
        if res.json()['rt_cd'] == '0':
            send_message(f"[매도 성공]{str(res.json())}")
            return True
        else:
            send_message(f"[매도 실패]{str(res.json())}")
            return False
    except Exception as ex:
        send_message(f"[매도 오류]{ex}")
        return False
    
symbol_list = ["005930","035720","000660","036630","166090","020150","001500","267250","489460","036540","131970"]
symbol_dict = {
    "005930": "삼성전자",
    # "092200": "디아이씨",
    "035720": "카카오",
    "000660": "sk하이닉스",
    "036630": "세종텔레콤",
    "166090": "하나머티리얼즈",
    "020150": "롯데에너지머티리얼즈",
    "001500": "현대차증권",
    "267250": "HD현대",
    "489460": "바이오비쥬",
    "036540": "SFA반도체",
    "131970": "두산테스나",
}
    
# 자동매매 시작
try:
    ACCESS_TOKEN = get_access_token()
            
    for i in symbol_list:
        send_message(f"{symbol_dict[i]} 목표가 = {int(get_target_price(i))} 원")

    # 매수 시각별 평단가 저장용 딕셔너리
    buy_prices = {}

    bought_list = []
    total_cash = get_balance()
    stock_dict, eval0 = get_stock_balance()
    for sym in stock_dict.keys():
        bought_list.append(sym)
    target_buy_count = 3
    buy_percent = 0.33
    buy_amount = total_cash * buy_percent
    soldout = False

    send_message("=== 국내 주식 자동매매 프로그램을 시작합니다 ===")
    last_notify_minute = -1  # 마지막 알림을 보낸 분(0, 30 등)
    print_stock_balance(stock_dict, eval0)
    while True:
        t_now = datetime.now()
        t_9 = t_now.replace(hour=9, minute=0, second=0, microsecond=0)
        t_start = t_now.replace(hour=9, minute=5, second=0, microsecond=0)
        t_sell = t_now.replace(hour=15, minute=15, second=0, microsecond=0)
        t_exit = t_now.replace(hour=15, minute=20, second=0,microsecond=0)
        today = datetime.today().weekday()
        if today == 5 or today == 6:
            send_message("주말이므로 프로그램을 종료합니다.")
            break
        if t_9 < t_now < t_start and soldout == False:
            for sym, qty in stock_dict.items():
                sell(sym, qty)
            soldout = True
            bought_list = []
            buy_prices = {}
            print_stock_balance(stock_dict, eval0)

        # 메인 매수/매도 구간
        if t_start < t_now < t_sell:
            stock_dict, eval0 = get_stock_balance()  # 최신화
            # 1. 7% 수익시 매도 로직
            for sym, qty in stock_dict.items():
                try:
                    if qty == 0:
                        continue
                    avg_price = None
                    # 잔고에서 매입가 추출
                    stock_info = stock_dict
                    if type(stock_info[sym]) == dict and 'pchs_avg_pric' in stock_info[sym]:
                        avg_price = float(stock_info[sym]['pchs_avg_pric'])
                    elif sym in buy_prices:
                        avg_price = buy_prices[sym]
                    else:
                        # 못찾으면 잔고 정보에 있는지 확인해보고 아니면 건너뜀
                        continue
                    cur_price = get_current_price(sym)
                    if avg_price and cur_price:
                        rate = (int(cur_price) - float(avg_price)) / float(avg_price)
                        if rate >= 0.07:
                            send_message(f"{symbol_dict.get(sym,sym)} 7% 수익 달성({avg_price} → {cur_price}). 전량 매도 진행.")
                            sell(sym, qty)
                            if sym in bought_list:
                                bought_list.remove(sym)
                            if sym in buy_prices:
                                del buy_prices[sym]
                except Exception as _ex_:
                    send_message(f"매도 7% 체크중 오류: {sym} - {_ex_}")

            # 2. 매수 로직
            for sym in symbol_list:
                if len(bought_list) < target_buy_count:
                    if sym in bought_list:
                        continue
                    target_price = get_target_price(sym)
                    current_price = get_current_price(sym)
                    if target_price is None or current_price is None:
                        continue
                    target_price = int(target_price)
                    current_price = int(current_price)
                    if target_price < current_price:
                        buy_qty = int(buy_amount // current_price)
                        if buy_qty > 0:
                            send_message(f"{symbol_dict[sym]} 목표가 달성({target_price} < {current_price}) 매수를 시도합니다.")
                            result = buy(sym, buy_qty)
                            if result:
                                soldout = False
                                bought_list.append(sym)
                                # 평단가 저장 (실시간 잔고정보 등으로 업데이트 가능)
                                buy_prices[sym] = current_price
                                stock_dict, eval0 = get_stock_balance()
                                                                
                    time.sleep(1)
            time.sleep(1)

            # 30분 마다(예: 9:00, 9:30, 10:00, ...) 잔고 등 알림
            if (t_now.minute % 30 == 0) and (last_notify_minute != t_now.minute):
                send_message(f"[알림] {t_now.strftime('%Y-%m-%d %H:%M')} 잔고 현황 업데이트")
                print_stock_balance(stock_dict, eval0)
                last_notify_minute = t_now.minute

        if t_sell < t_now < t_exit:
            if soldout == False:
                stock_dict, eval0 = get_stock_balance()
                for sym, qty in stock_dict.items():
                    sell(sym, qty)
                soldout = True
                bought_list = []
                buy_prices = {}
                time.sleep(1)
        if t_exit < t_now:
            send_message("프로그램을 종료합니다.")
            break
except Exception as e:
    send_message(f"[오류 발생]{e}")
    exc_type, exc_value, exc_traceback = sys.exc_info()
    traceback.print_exception(exc_type, exc_value, exc_traceback)
    time.sleep(1)

{'content': '[2025-12-16 14:48:36] saved token loading'}
{'content': '[2025-12-16 14:48:37] 삼성전자 목표가 = 105500 원'}
{'content': '[2025-12-16 14:48:37] 카카오 목표가 = 60300 원'}
{'content': '[2025-12-16 14:48:38] sk하이닉스 목표가 = 559250 원'}
{'content': '[2025-12-16 14:48:38] 세종텔레콤 목표가 = 13095 원'}
{'content': '[2025-12-16 14:48:38] 하나머티리얼즈 목표가 = 43125 원'}
{'content': '[2025-12-16 14:48:39] 롯데에너지머티리얼즈 목표가 = 35825 원'}
{'content': '[2025-12-16 14:48:39] 현대차증권 목표가 = 8205 원'}
{'content': '[2025-12-16 14:48:40] HD현대 목표가 = 205750 원'}
{'content': '[2025-12-16 14:48:40] 바이오비쥬 목표가 = 12865 원'}
{'content': '[2025-12-16 14:48:40] SFA반도체 목표가 = 4035 원'}
{'content': '[2025-12-16 14:48:41] 두산테스나 목표가 = 42350 원'}
{'content': '[2025-12-16 14:48:41] 주문 가능 현금 잔고: 35,827원'}
{'content': '[2025-12-16 14:48:42] === 국내 주식 자동매매 프로그램을 시작합니다 ==='}
{'content': '[2025-12-16 14:48:42] ==== 주식 보유잔고 ===='}
{'content': '[2025-12-16 14:48:42] 세종텔레콤(036630): 1주'}
{'content': '[2025-12-16 14:48:43] 주식 평가 금액: 13320원'}
{'content': '[2025-12-16 14:48:43] 평가 손익 합계: 220원'}
{'content': '[2025-12-16 14:48:44] 총 평가 금액: 49147원'}
{'content': '[2025-12-16 14:48:44] ====================='}

KeyboardInterrupt:

In [ ]:
# sell(code = "001500")

{'content': "[2025-11-25 14:38:26] [매도 성공]{'rt_cd': '0', 'msg_cd': 'APBK0013', 'msg1': '주문 전송 완료 되었습니다.', 'output': {'KRX_FWDG_ORD_ORGNO': '91250', 'ODNO': '0016424300', 'ORD_TMD': '143826', 'SOR_ODNO': ''}}"}

True

In [7]:
def get_stock_balance():
    """
    주식 계좌의 보유 주식 종목과 수량을 조회하여 반환합니다.
    반환값: {종목코드(str): 보유수량(int)}
    """
    global ACCESS_TOKEN
    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-balance"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8434R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "",
        "INQR_DVSN": "02",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": "",
        "CTX_AREA_NK100": "",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output1" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[주식 잔고조회 실패] {msg}")
        raise ValueError(f"주식 잔고 조회 실패: {msg}")

    stock_list = data["output1"]
    evaluation = data.get("output2", [])
    stock_dict = {} # dict[str, int]
    # send_message("====주식 보유잔고====")
    
    for stock in stock_list:
        try:
            qty = int(stock.get("hldg_qty", "0"))
        except (TypeError, ValueError):
            qty = 0
        if qty > 0:
            pdno = stock.get("pdno", "")
            stock_dict[pdno] = qty
            # send_message(f"{stock.get('prdt_name', '미상')}({pdno}): {qty}주")
            # time.sleep(0.1)

    if evaluation:
        eval0 = evaluation[0]
    #     send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
    #     time.sleep(0.1)
    #     send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
    #     time.sleep(0.1)
    #     send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
    #     time.sleep(0.1)
    # send_message("=====================")

    return stock_dict, eval0

stock_dict, eval0 = get_stock_balance()
send_message("====주식 보유잔고====")
for pdno in stock_dict:    
    send_message(f"{symbol_dict[pdno]}({pdno}): {stock_dict[pdno]}주")
    time.sleep(0.1)
send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
time.sleep(0.1)
send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
time.sleep(0.1)
send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
time.sleep(0.1)
send_message("=====================")

if int(eval0.get('evlu_pfls_smtl_amt', '0')) >= 200:
    sell('036630')

{'content': '[2025-12-16 14:49:18] ====주식 보유잔고===='}
{'content': '[2025-12-16 14:49:18] 세종텔레콤(036630): 1주'}
{'content': '[2025-12-16 14:49:19] 주식 평가 금액: 13320원'}
{'content': '[2025-12-16 14:49:19] 평가 손익 합계: 220원'}
{'content': '[2025-12-16 14:49:19] 총 평가 금액: 49147원'}
{'content': '[2025-12-16 14:49:20] ====================='}
{'content': "[2025-12-16 14:49:20] [매도 성공]{'rt_cd': '0', 'msg_cd': 'APBK0013', 'msg1': '주문 전송 완료 되었습니다.', 'output': {'KRX_FWDG_ORD_ORGNO': '91250', 'ODNO': '0020495100', 'ORD_TMD': '144920', 'SOR_ODNO': ''}}"}

In [ ]:
sell('036630')

{'content': "[2025-12-03 15:21:43] [매도 성공]{'rt_cd': '0', 'msg_cd': 'APBK0013', 'msg1': '주문 전송 완료 되었습니다.', 'output': {'KRX_FWDG_ORD_ORGNO': '91250', 'ODNO': '0018823300', 'ORD_TMD': '152143', 'SOR_ODNO': ''}}"}

True

# 최종코드 V2

In [2]:
import json
import os
import sys
import traceback
from datetime import datetime
import time
import yaml
import requests
import shutil
import pandas as pd


# yaml 파일 로딩
with open('config.yaml', encoding='UTF-8') as f:
    _cfg = yaml.load(f, Loader=yaml.FullLoader)
APP_KEY = _cfg['APP_KEY']
APP_SECRET = _cfg['APP_SECRET']
ACCESS_TOKEN = ""
CANO = _cfg['CANO']
ACNT_PRDT_CD = _cfg['ACNT_PRDT_CD']
DISCORD_WEBHOOK_URL = _cfg['DISCORD_WEBHOOK_URL']
URL_BASE = _cfg['URL_BASE']

# 디스코드에 메시지 전송 함수
def send_message(msg):
    """
    디스코드 메세지를 전송합니다.
    msg: 전송할 메시지(문자열)
    """
    now = datetime.now()
    message = {"content": f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] {str(msg)}"}
    try:
        requests.post(DISCORD_WEBHOOK_URL, data=message)
    except Exception as e:
        print(f"디스코드 전송 에러: {e}")
    print(message)

# 토큰 파일 경로 설정
config_root = os.path.join(os.path.expanduser("~"), "workspace", "mini_project")
token_tmp = os.path.join(config_root, f"KIS{datetime.today().strftime('%Y%m%d')}")

# 접근토큰 관리하는 파일 존재여부 체크, 없으면 생성
if not os.path.exists(token_tmp):
    with open(token_tmp, "w+"):
        pass

# 토큰 저장
def save_token(my_token, my_expired):   
    """
    발급받은 토큰과 만료일시를 파일로 저장합니다.
    my_token: 토큰 문자열
    my_expired: 만료일시 (문자열, "%Y-%m-%d %H:%M:%S" 형식)
    """
    valid_date = datetime.strptime(my_expired, "%Y-%m-%d %H:%M:%S")
    with open(token_tmp, "w", encoding="utf-8") as f:
        f.write(f"token: {my_token}\n")
        f.write(f"valid-date: {valid_date}\n")
    send_message(f"token file name [{token_tmp}] stored")

# 예전 토큰 파일 expired 폴더로 이동
def move_old_tokens_to_expired():
    """
    오늘 이전 날짜의 모든 KIS 토큰 파일을 expired 폴더로 이동시킵니다.
    """
    try:
        expired_dir = os.path.join(config_root, "expired")
        if not os.path.exists(expired_dir):
            os.makedirs(expired_dir)
        today = datetime.today().date()
        # config_root 하위의 모든 토큰 파일을 순회
        for fname in os.listdir(config_root):
            if fname.startswith("KIS") and fname[3:11].isdigit():
                token_date_str = fname[3:11]
                try:
                    token_date = datetime.strptime(token_date_str, "%Y%m%d").date()
                except Exception:
                    continue  # 파일명이 날짜 형식에 맞지 않으면 스킵

                if token_date < today:
                    token_file_path = os.path.join(config_root, fname)
                    # 파일명에 타임스탬프 추가하여 이동 (중복 방지)
                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                    expired_file_path = os.path.join(expired_dir, f"{timestamp}_{fname}")
                    try:
                        shutil.move(token_file_path, expired_file_path)
                        send_message(f"오늘 이전({token_date})에 발급된 토큰 파일을 {expired_file_path}로 이동했습니다.")
                    except Exception as e:
                        send_message(f"{fname} 파일 이동 중 오류: {str(e)}")
    except Exception as e:
        send_message(f"만료된 토큰 파일 이동 작업 전체에서 오류 발생: {str(e)}")

# 토큰 불러오기 (만료체크)
def read_token():
    """
    저장된 토큰이 있으면 파일에서 읽어서 유효하면 반환,
    만료되었으면 None 반환 및 만료된 토큰 파일 expired로 이동
    """
    try:
        # yaml로 파싱 불안정하므로 직접 파싱
        token = None
        valid_date = None
        with open(token_tmp, encoding="UTF-8") as f:
            for line in f:
                if "token:" in line:
                    token = line.split(":",1)[1].strip()
                elif "valid-date:" in line:
                    valid_date_str = line.split(":",1)[1].strip()
                    valid_date = datetime.strptime(valid_date_str, "%Y-%m-%d %H:%M:%S")
        if token and valid_date:
            now = datetime.now()
            if valid_date > now:
                return token
            else:
                send_message("token expired")
                move_old_tokens_to_expired()
                return None
        return None
    except Exception:
        return None

# 토큰 발급 (저장된 토큰 있으면 재사용)
def get_access_token():
    """
    저장된 토큰 파일에서 유효한 토큰을 반환, 없거나 만료된 경우 새로 발급 후 저장 및 반환
    """
    global ACCESS_TOKEN
    saved_token = read_token()
    if saved_token is not None:
        send_message(f"saved token loading")
        ACCESS_TOKEN = saved_token
        move_old_tokens_to_expired()
        return saved_token
    headers = {"content-type": "application/json"}
    body = {
        "grant_type": "client_credentials",
        "appkey": APP_KEY,
        "appsecret": APP_SECRET
    }
    PATH = "oauth2/tokenP"
    URL = f"{URL_BASE}/{PATH}"
    res = requests.post(URL, headers=headers, data=json.dumps(body))
    if res.status_code == 200:
        ACCESS_TOKEN = res.json()["access_token"]
        my_expired = res.json()["access_token_token_expired"]
        save_token(ACCESS_TOKEN, my_expired)
        return ACCESS_TOKEN
    else:
        send_message(f"")
        print("토큰 발급 실패!")
        return None

# 주식 잔고 조회
def get_stock_balance():
    """
    주식 계좌의 보유 주식 종목과 수량을 조회하여 반환합니다.
    반환값: {종목코드(str): 보유수량(int)}
    """
    global ACCESS_TOKEN
    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-balance"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8434R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "AFHR_FLPR_YN": "N",
        "OFL_YN": "",
        "INQR_DVSN": "02",
        "UNPR_DVSN": "01",
        "FUND_STTL_ICLD_YN": "N",
        "FNCG_AMT_AUTO_RDPT_YN": "N",
        "PRCS_DVSN": "01",
        "CTX_AREA_FK100": "",
        "CTX_AREA_NK100": "",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output1" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[주식 잔고조회 실패] {msg}")
        raise ValueError(f"주식 잔고 조회 실패: {msg}")

    stock_list = data["output1"]
    evaluation = data.get("output2", [])
    stock_dict = {} # dict[str, int]
    # send_message("====주식 보유잔고====")
    
    for stock in stock_list:
        try:
            qty = int(stock.get("hldg_qty", "0"))
        except (TypeError, ValueError):
            qty = 0
        if qty > 0:
            pdno = stock.get("pdno", "")
            stock_dict[pdno] = qty
            # send_message(f"{stock.get('prdt_name', '미상')}({pdno}): {qty}주")
            time.sleep(0.1)

    if evaluation:
        eval0 = evaluation[0]
    #     send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
    #     time.sleep(0.1)
    #     send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
    #     time.sleep(0.1)
    #     send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
    #     time.sleep(0.1)
    # send_message("=====================")

    return stock_dict, eval0


def print_stock_balance(stock_dict, eval0):
    
    send_message("==== 주식 보유잔고 ====")
    for pdno in stock_dict:    
        send_message(f"{symbol_dict[pdno]}({pdno}): {stock_dict[pdno]}주")
        time.sleep(0.1)
    send_message(f"주식 평가 금액: {eval0.get('scts_evlu_amt', '0')}원")
    time.sleep(0.1)
    send_message(f"평가 손익 합계: {eval0.get('evlu_pfls_smtl_amt', '0')}원")
    time.sleep(0.1)
    send_message(f"총 평가 금액: {eval0.get('tot_evlu_amt', '0')}원")
    time.sleep(0.1)
    send_message("=====================")
    return






# 현금 잔고 조회
def get_balance(price_code="005930", order_price="65500"):
    """
    계좌의 주문 가능 현금 잔고를 integer로 반환합니다.
    price_code: 조회할 종목코드(기본 005930), order_price: 가격(기본 65500)
    """
    
    global ACCESS_TOKEN
    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")

    PATH = "uapi/domestic-stock/v1/trading/inquire-psbl-order"
    URL = f"{URL_BASE}/{PATH}"
    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "TTTC8908R",
        "custtype": "P",
    }
    params = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": price_code,
        "ORD_UNPR": order_price,
        "ORD_DVSN": "01",
        "CMA_EVLU_AMT_ICLD_YN": "Y",
        "OVRS_ICLD_YN": "Y",
    }

    res = requests.get(URL, headers=headers, params=params)
    data = res.json()

    if res.status_code != 200 or "output" not in data:
        msg = data.get("msg1", res.text)
        send_message(f"[현금 잔고조회 실패] {msg}")
        raise ValueError(f"현금 잔고 조회 실패: {msg}")

    cash = int(data["output"]["ord_psbl_cash"])
    send_message(f"주문 가능 현금 잔고: {cash:,}원")
    return cash



# 현재가 조회
def get_current_price(stock_no="005930"):
    """
    입력한 종목의 현재가를 조회 후 문자열(가격)로 반환합니다.
    stock_no: 종목코드(문자열)
    """
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급에 실패했습니다.")
    
    PATH = "uapi/domestic-stock/v1/quotations/inquire-price"
    URL = f"{URL_BASE}/{PATH}"

    # 헤더 설정
    headers = {
        "Content-Type": "application/json", 
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010100"
    }

    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": stock_no
    }

    # 호출
    res = requests.get(URL, headers=headers, params=params)
    try:
        if res.status_code == 200 and res.json()["rt_cd"] == "0":
            return res.json()['output']['stck_prpr']
    except Exception:
        pass
    print("Error Code : " + str(res.status_code) + " | " + res.text)
    send_message(f"Error Code : {str(res.status_code)} | {res.text}")
    return None



####
####
# 지정한 종목코드의 과거 ~ 오늘까지 날짜별 시세 (종가, 고가, 저가, 시가, 거래량)를 DataFrame으로 반환
def get_daily_price_df(code: str = "005930") -> pd.DataFrame:
    """
    주어진 종목 코드의 오늘까지(최신 포함) 일자별 시세를 DataFrame으로 반환합니다.
    DataFrame 컬럼: ['date', 'close', 'high', 'low', 'open', 'volume']

    Args:
        code (str): 조회할 종목의 코드. 6자리 숫자 문자열.

    Returns:
        pd.DataFrame: 날짜 기준으로 정렬된 시세 데이터프레임.  
            col = ['date','close','high','low','open','volume']
            date: YYYYMMDD(문자열)
    """
    global ACCESS_TOKEN

    if not ACCESS_TOKEN:
        ACCESS_TOKEN = get_access_token()
        if not ACCESS_TOKEN:
            raise RuntimeError("ACCESS_TOKEN 발급 실패")

    PATH = "uapi/domestic-stock/v1/quotations/inquire-daily-price"
    URL = f"{URL_BASE}/{PATH}"

    headers = {
        "Content-Type": "application/json",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appKey": APP_KEY,
        "appSecret": APP_SECRET,
        "tr_id": "FHKST01010400",  # 일자별 시세조회
    }
    params = {
        "fid_cond_mrkt_div_code": "J",
        "fid_input_iscd": code,
        "fid_org_adj_prc": "1",
        "fid_period_div_code": "D",
    }

    res = requests.get(URL, headers=headers, params=params, timeout=10)
    if res.status_code != 200:
        print("API 호출 실패")
        print("res.status_code: ", res.status_code)
        return None

    data = res.json()
    rows = data.get("output", []) or []
    if not rows:
        return None

    # 원하는 컬럼: 날짜, 종가, 고가, 저가, 시가, 거래량
    records = []
    for row in rows:
        records.append({
            'Date': row.get('stck_bsop_date'),   # YYYYMMDD
            'Close': int(row.get('stck_clpr', '0')),
            'High': int(row.get('stck_hgpr', '0')),
            'Low': int(row.get('stck_lwpr', '0')),
            'Open': int(row.get('stck_oprc', '0')),
            'Volume': int(row.get('acml_vol', '0')),
        })
    # 날짜 내림차순이 보통이므로 오름차순 정렬
    df = pd.DataFrame(records)
    df = df.sort_values('Date').reset_index(drop=True)
    return df


# RSI 계산
def compute_rsi(series, period=7):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=period, min_periods=period).mean()
    avg_loss = loss.rolling(window=period, min_periods=period).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi


# MACD 계산
def compute_macd(series, fast=8, slow=17, signal=5):
    """
    예시 조합 1: (5, 13, 3) → 빠른 반응, 스캘핑에 적합
    예시 조합 2: (8, 17, 5) → 약간의 안정성 확보, 데이 트레이딩에 적합
    """
    ema_fast = series.ewm(span=fast, adjust=False).mean()
    ema_slow = series.ewm(span=slow, adjust=False).mean()
    macd = ema_fast - ema_slow
    macd_signal = macd.ewm(span=signal, adjust=False).mean()
    return macd, macd_signal


# 매매 신호 출력
def trading_signal(df, rsi_fast_column='RSI_fast', rsi_slow_column='RSI_slow', macd_column='MACD', signal_column='Signal'):
    """
    df: DataFrame with 'RSI_fast', 'RSI_slow', 'MACD', 'Signal' columns
    return: pd.Series of 'Buy', 'Sell', or 'Hold'
    """
    signals = []
    for i in range(1, len(df)):
        # .iloc[]로 스칼라값 추출 → Series가 아닌 float/np.nan
        rsi_fast = df[rsi_fast_column].iloc[i]
        rsi_slow = df[rsi_slow_column].iloc[i]
        macd = df[macd_column].iloc[i]
        macd_prev = df[macd_column].iloc[i-1]
        signal = df[signal_column].iloc[i]
        signal_prev = df[signal_column].iloc[i-1]
        
        if pd.isna(rsi_fast) or pd.isna(rsi_slow) or pd.isna(macd) or pd.isna(macd_prev) or pd.isna(signal) or pd.isna(signal_prev):
            signals.append('Hold')
            continue

        # Buy condition
        if (rsi_fast < 30) and (macd > signal) and (macd_prev < signal_prev) and (rsi_fast > rsi_slow):
            signals.append('Buy')
        # Sell condition
        elif (rsi_fast > 70) and (macd < signal) and (macd_prev > signal_prev) and (rsi_fast < rsi_slow):
            signals.append('Sell')
        else:
            signals.append('Hold')
    signals = ['Hold'] + signals    # 첫 데이터는 비교 불가이므로 Hold
    return pd.Series(signals, index=df.index)

    
# 목표가 지정
def get_target_price(code="005930"):
    """매수 시그널 발생 시 해당 일의 종가를 매수가로 반환"""
    df['Trade_signal'] = trading_signal(df, 'RSI_fast', 'RSI_slow', 'MACD', 'Signal')
    buy_signals = df[df['Trade_signal'] == 'Buy']
    print(df)
    print(buy_signals)
    if buy_signals.empty:
        return None  # 매수 시그널이 없는 경우 None 반환
    # 매수 신호가 여러 번이면 첫번째 or 마지막 등 정책에 따라 변경 가능
    # 여기서는 가장 최근의(마지막) 매수 신호를 사용
    last_buy_signal = buy_signals.iloc[-1]
    target_price = last_buy_signal['Close']
    return target_price


# 매수
def buy(code="005930", qty="1"):
    """
    특정 종목을 지정한 수량만큼 시장가로 매수. 성공시 True, 실패시 False 반환
    code: 종목코드, qty: 수량 (문자열 또는 정수)
    """
    global ACCESS_TOKEN
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": str(int(qty)),
        "ORD_UNPR": "0",
    }
    headers = {
        "Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0012U",    # (구)TTTC0802U → (신)TTTC0012U
        "custtype":"P",
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    try:
        if res.json()['rt_cd'] == '0':
            send_message(f"[매수 성공]{str(res.json())}")
            return True
        else:
            send_message(f"[매수 실패]{str(res.json())}")
            return False
    except Exception as ex:
        send_message(f"[매수 오류]{ex}")
        return False

# 매도
def sell(code="005930", qty="1"):
    """
    특정 종목을 지정한 수량만큼 시장가로 매도. 성공시 True, 실패시 False 반환
    code: 종목코드, qty: 수량 (문자열 또는 정수)
    """
    global ACCESS_TOKEN
    PATH = "uapi/domestic-stock/v1/trading/order-cash"
    URL = f"{URL_BASE}/{PATH}"
    data = {
        "CANO": CANO,
        "ACNT_PRDT_CD": ACNT_PRDT_CD,
        "PDNO": code,
        "ORD_DVSN": "01",
        "ORD_QTY": qty,
        "ORD_UNPR": "0",
    }
    headers = {
        "Content-Type":"application/json", 
        "authorization":f"Bearer {ACCESS_TOKEN}",
        "appKey":APP_KEY,
        "appSecret":APP_SECRET,
        "tr_id":"TTTC0011U",    # (구)TTTC0801U → (신)TTTC0011U
        "custtype":"P",
    }
    res = requests.post(URL, headers=headers, data=json.dumps(data))
    try:
        if res.json()['rt_cd'] == '0':
            send_message(f"[매도 성공]{str(res.json())}")
            return True
        else:
            send_message(f"[매도 실패]{str(res.json())}")
            return False
    except Exception as ex:
        send_message(f"[매도 오류]{ex}")
        return False


# RSI + MACD 조건 자동매매: 신호 발생 종가 또는 다음날 시초가 진입 선택 & 익절(+7%)·손절(−3%) 자동 적용
ENTRY_METHOD = "close"  # "close" → 신호 발생일 종가 기준 즉시 진입, "open" → 다음 거래일 시초가 진입
TAKE_PROFIT_RATE = 0.07
STOP_LOSS_RATE = -0.03
CHECK_INTERVAL_SEC = 3
LOOKBACK_DAYS = 120
TARGET_BUY_COUNT = 3
BUY_PERCENT = 0.33
MAX_OPEN_DELAY_DAYS = 3  # 시초가 대기 주문 만료 한도 (거래일 기준)



def prepare_indicator_df(symbol: str, lookback: int = LOOKBACK_DAYS):
    """
    주어진 종목(symbol)에 대한 가격 데이터를 조회하고,
    RSI(Momentum)와 MACD(Trend Following) 지표 및 시그널 열을 추가한 데이터프레임을 반환합니다.

    Args:
        symbol (str): 조회할 종목의 심볼코드(예: "005930").
        lookback (int): 조회할 데이터의 기간(일 단위, 최근 N개의 데이터).

    Returns:
        pd.DataFrame or None: 지표 컬럼이 추가된 DataFrame. 데이터가 없으면 None 반환.
    """
    df = get_daily_price_df(symbol)
    if df is None or df.empty:
        return None
    df = df.tail(lookback).copy()
    df['RSI_fast'] = compute_rsi(df['Close'], period=7)
    df['RSI_slow'] = compute_rsi(df['Close'], period=14)
    macd_line, macd_signal = compute_macd(df['Close'], fast=8, slow=17, signal=5)
    df['MACD'] = macd_line
    df['Signal'] = macd_signal
    df['Trade_signal'] = trading_signal(df, 'RSI_fast', 'RSI_slow', 'MACD', 'Signal')
    return df


def parse_price(value):
    """
    임의의 값(문자, 실수, 정수 등)을 정수 가격 형태로 변환합니다.
    예외 발생 시 None을 반환합니다.

    Args:
        value: 변환할 값 (str, float 등).

    Returns:
        int or None: 변환된 가격(정수), 변환 불가시 None.
    """
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def determine_buy_qty(price: int, max_cash: float):
    """
    현재 가격과 주문 가능 금액을 기준으로, 매수 가능한 최대 수량(주식 수)을 계산합니다.

    Args:
        price (int): 매수 희망 가격 (정수).
        max_cash (float): 1회 거래에 사용할 최대 현금(예: total_cash * BUY_PERCENT).

    Returns:
        int: 매수 수량. 현금 부족/가격 미정의/오류시 0 반환.
    """
    if price is None or price <= 0:
        return 0
    try:
        available_cash = get_balance()
    except Exception as balance_error:
        send_message(f"[현금 조회 실패]{balance_error}")
        return 0
    buy_cash = min(max_cash, available_cash)
    return int(buy_cash // price)


def bootstrap_positions():
    """
    현재 보유중인 주식을 기반으로 active_positions 딕셔너리를 초기화합니다.
    각 종목을 현재가 기준 진입(bootstrap) 처리로 간주합니다.

    Returns:
        dict: symbol을 key로 하고, 수량/진입가/진입시간/진입방법 등의 정보를 가진 포지션 딕셔너리.
    """
    positions = {}
    stock_dict, eval0 = get_stock_balance()
    for sym, qty in stock_dict.items():
        now_price = parse_price(get_current_price(sym))
        if now_price is None:
            continue
        positions[sym] = {
            "qty": qty,
            "entry_price": now_price,
            "entry_date": datetime.now(),
            "entry_method": "bootstrap",
        }
    return positions



symbol_dict = {
    "005930": "삼성전자",
    # "092200": "디아이씨",
    "035720": "카카오",
    "000660": "sk하이닉스",
    "036630": "세종텔레콤",
    "166090": "하나머티리얼즈",
    "020150": "롯데에너지머티리얼즈",
    "001500": "현대차증권",
    "267250": "HD현대",
    "489460": "바이오비쥬",
    "036540": "SFA반도체",
    "131970": "두산테스나",
}
symbol_list = list(symbol_dict.keys())


try:
    entry_mode = ENTRY_METHOD.lower()
    if entry_mode not in ("close", "open"):
        raise ValueError("ENTRY_METHOD must be either 'close' or 'open'.")

    ACCESS_TOKEN = get_access_token()

    total_cash = get_balance()
    max_trade_cash = total_cash * BUY_PERCENT   # 0.33
    stock_dict, eval0 = get_stock_balance()  # 최신화
    active_positions = bootstrap_positions()
    pending_open_entries = {}
    last_signal_dates = {}

    send_message(f"=== 자동매매 시작 (entry={entry_mode}) ===")
    
    print_stock_balance(stock_dict, eval0)

    while True:
        t_now = datetime.now()
        today_idx = t_now.weekday()
        today_str = t_now.strftime("%Y%m%d")
        today_date = t_now.date()
        entry_window_start = t_now.replace(hour=9, minute=5, second=0, microsecond=0)
        exit_watch = t_now.replace(hour=15, minute=15, second=0, microsecond=0)
        hard_exit = t_now.replace(hour=15, minute=20, second=0, microsecond=0)

        if today_idx >= 5:
            send_message("주말입니다. 자동매매 종료.")
            break

        if t_now >= hard_exit:
            for sym in list(active_positions.keys()):
                qty = active_positions[sym]['qty']
                if sell(sym, qty):
                    send_message(f"{symbol_dict.get(sym, sym)} 장마감 강제청산")
                active_positions.pop(sym, None)
            pending_open_entries.clear()
            send_message("장마감, 프로그램 종료")
            break

        # RSI + MACD 진입 감시 (신호 발생일 종가 기준)
        if entry_window_start <= t_now <= exit_watch and len(active_positions) < TARGET_BUY_COUNT:
            stock_dict, eval0 = get_stock_balance()  # 최신화
            for sym in symbol_list:
                if sym in active_positions or len(active_positions) >= TARGET_BUY_COUNT:
                    continue
                try:
                    indicator_df = prepare_indicator_df(sym)
                except Exception as indicator_error:
                    send_message(f"{symbol_dict.get(sym, sym)} 지표 계산 실패: {indicator_error}")
                    continue
                if indicator_df is None or indicator_df.empty:
                    continue
                latest_signal = indicator_df['Trade_signal'].iloc[-1]
                if pd.isna(latest_signal):
                    continue
                signal_date = str(indicator_df['Date'].iloc[-1])
                if latest_signal != 'Buy' or signal_date != today_str:
                    continue
                if last_signal_dates.get(sym) == signal_date:
                    continue
                last_signal_dates[sym] = signal_date

                if entry_mode == "open":
                    pending_open_entries[sym] = {"signal_date": signal_date}
                    send_message(f"{symbol_dict.get(sym, sym)} 매수 신호 발생 - 다음날 시초가 진입 대기")
                    continue

                exec_price = parse_price(get_current_price(sym))
                if exec_price is None:
                    print("exec_price is None")
                    continue
                qty = determine_buy_qty(exec_price, max_trade_cash)
                if qty <= 0:
                    print(f"qty = {qty}")
                    continue
                if buy(sym, qty):
                    active_positions[sym] = {
                        "qty": qty,
                        "entry_price": exec_price,
                        "entry_date": datetime.now(),
                        "entry_method": entry_mode,
                    }
                    send_message(f"{symbol_dict.get(sym, sym)} RSI+MACD 종가 진입({exec_price}원, {qty}주)")
                    print_stock_balance(stock_dict, eval0)

        # 다음날 시초가 진입 처리
        if entry_mode == "open" and entry_window_start <= t_now <= exit_watch:
            stock_dict, eval0 = get_stock_balance()  # 최신화
            for sym, info in list(pending_open_entries.items()):
                if sym in active_positions:
                    pending_open_entries.pop(sym, None)
                    continue
                try:
                    signal_dt = datetime.strptime(info['signal_date'], "%Y%m%d").date()
                except (TypeError, ValueError):
                    pending_open_entries.pop(sym, None)
                    continue
                delay_days = (today_date - signal_dt).days
                if delay_days <= 0:
                    continue
                if delay_days > MAX_OPEN_DELAY_DAYS:
                    pending_open_entries.pop(sym, None)
                    continue
                if len(active_positions) >= TARGET_BUY_COUNT:
                    continue
                exec_price = parse_price(get_current_price(sym))
                if exec_price is None:
                    continue
                qty = determine_buy_qty(exec_price, max_trade_cash)
                if qty <= 0:
                    continue
                if buy(sym, qty):
                    active_positions[sym] = {
                        "qty": qty,
                        "entry_price": exec_price,
                        "entry_date": datetime.now(),
                        "entry_method": "open",
                    }
                    pending_open_entries.pop(sym, None)
                    send_message(f"{symbol_dict.get(sym, sym)} 시초가 진입 완료({exec_price}원, {qty}주)")
                    print_stock_balance(stock_dict, eval0)

        # 익절/손절 감시
        for sym in list(active_positions.keys()):
            now_price = parse_price(get_current_price(sym))
            if now_price is None:
                continue
            entry_price = active_positions[sym]['entry_price']
            if entry_price <= 0:
                continue
            change = (now_price - entry_price) / entry_price
            qty = active_positions[sym]['qty']
            if change >= TAKE_PROFIT_RATE:
                if sell(sym, qty):
                    send_message(
                        f"{symbol_dict.get(sym, sym)} +{TAKE_PROFIT_RATE*100:.1f}% 익절 ({entry_price}→{now_price})"
                    )
                    active_positions.pop(sym, None)
            elif change <= STOP_LOSS_RATE:
                if sell(sym, qty):
                    send_message(
                        f"{symbol_dict.get(sym, sym)} {STOP_LOSS_RATE*100:.1f}% 손절 ({entry_price}→{now_price})"
                    )
                    active_positions.pop(sym, None)

        time.sleep(CHECK_INTERVAL_SEC)

except Exception as e:
    send_message(f"[오류 발생]{e}")
    import traceback, sys
    exc_type, exc_value, exc_traceback = sys.exc_info()
    traceback.print_exception(exc_type, exc_value, exc_traceback)
    time.sleep(1)



# 자동매매 시작
# try:
#     ACCESS_TOKEN = get_access_token()
            
#     for i in symbol_list:
#         send_message(f"{symbol_dict[i]} 목표가 = {int(get_target_price(i))} 원")

#     bought_list = []
#     total_cash = get_balance()
#     stock_dict, eval0 = get_stock_balance()
#     for sym in stock_dict.keys():
#         bought_list.append(sym)
#     target_buy_count = 3
#     buy_percent = 0.33
#     buy_amount = total_cash * buy_percent
#     soldout = False

    
#     send_message("===국내 주식 자동매매 프로그램을 시작합니다===")
#     while True:
#         t_now = datetime.now()
#         t_9 = t_now.replace(hour=9, minute=0, second=0, microsecond=0)
#         t_start = t_now.replace(hour=9, minute=5, second=0, microsecond=0)
#         t_sell = t_now.replace(hour=15, minute=15, second=0, microsecond=0)
#         t_exit = t_now.replace(hour=15, minute=20, second=0,microsecond=0)
#         today = datetime.today().weekday()
#         if today == 5 or today == 6:
#             send_message("주말이므로 프로그램을 종료합니다.")
#             break
#         if t_9 < t_now < t_start and soldout == False:
#             for sym, qty in stock_dict.items():
#                 sell(sym, qty)
#             soldout = True
#             bought_list = []
#             stock_dict = get_stock_balance()
#         if t_start < t_now < t_sell:
#             for sym in symbol_list:
#                 if len(bought_list) < target_buy_count:
#                     if sym in bought_list:
#                         continue
#                     target_price = get_target_price(sym)
#                     current_price = get_current_price(sym)
#                     if target_price is None or current_price is None:
#                         continue
#                     target_price = int(target_price)
#                     current_price = int(current_price)
#                     if target_price < current_price:
#                         buy_qty = int(buy_amount // current_price)
#                         if buy_qty > 0:
#                             send_message(f"{symbol_dict[sym]} 목표가 달성({target_price} < {current_price}) 매수를 시도합니다.")
#                             result = buy(sym, buy_qty)
#                             if result:
#                                 soldout = False
#                                 bought_list.append(sym)
#                                 get_stock_balance()
#                     time.sleep(1)
#             time.sleep(1)
#             if t_now.minute == 30 and t_now.second <= 5: 
#                 get_stock_balance()
#                 time.sleep(5)
#         if t_sell < t_now < t_exit:
#             if soldout == False:
#                 stock_dict = get_stock_balance()
#                 for sym, qty in stock_dict.items():
#                     sell(sym, qty)
#                 soldout = True
#                 bought_list = []
#                 time.sleep(1)
#         if t_exit < t_now:
#             send_message("프로그램을 종료합니다.")
#             break
# except Exception as e:
#     send_message(f"[오류 발생]{e}")
#     exc_type, exc_value, exc_traceback = sys.exc_info()
#     traceback.print_exception(exc_type, exc_value, exc_traceback)
#     time.sleep(1)

{'content': '[2025-12-15 10:52:45] saved token loading'}
{'content': '[2025-12-15 10:52:45] 주문 가능 현금 잔고: 48,927원'}
{'content': '[2025-12-15 10:52:46] === 자동매매 시작 (entry=close) ==='}
{'content': '[2025-12-15 10:52:46] ==== 주식 보유잔고 ===='}
{'content': '[2025-12-15 10:52:46] 주식 평가 금액: 0원'}
{'content': '[2025-12-15 10:52:47] 평가 손익 합계: 0원'}
{'content': '[2025-12-15 10:52:47] 총 평가 금액: 48927원'}
{'content': '[2025-12-15 10:52:48] ====================='}
{'content': '[2025-12-15 10:54:04] [주식 잔고조회 실패] 원장에서 허용 가능한 초당 거래건수를 초과하였습니다.'}
{'content': '[2025-12-15 10:54:05] [오류 발생]주식 잔고 조회 실패: 원장에서 허용 가능한 초당 거래건수를 초과하였습니다.'}

Traceback (most recent call last):
  File "/tmp/ipykernel_2985/2057851540.py", line 711, in <module>
    stock_dict, eval0 = get_stock_balance()  # 최신화
  File "/tmp/ipykernel_2985/2057851540.py", line 194, in get_stock_balance
    raise ValueError(f"주식 잔고 조회 실패: {msg}")
ValueError: 주식 잔고 조회 실패: 원장에서 허용 가능한 초당 거래건수를 초과하였습니다.

In [3]:
print_stock_balance(stock_dict, eval0)

{'content': '[2025-12-15 10:54:33] ==== 주식 보유잔고 ===='}
{'content': '[2025-12-15 10:54:33] 주식 평가 금액: 0원'}
{'content': '[2025-12-15 10:54:33] 평가 손익 합계: 0원'}
{'content': '[2025-12-15 10:54:34] 총 평가 금액: 48927원'}
{'content': '[2025-12-15 10:54:34] ====================='}

In [ ]:
# RSI + MACD 조건 자동매매: 신호 발생 종가 또는 다음날 시초가 진입 선택 & 익절(+7%)·손절(−3%) 자동 적용
ENTRY_METHOD = "close"  # "close" → 신호 발생일 종가 기준 즉시 진입, "open" → 다음 거래일 시초가 진입
TAKE_PROFIT_RATE = 0.07
STOP_LOSS_RATE = -0.03
CHECK_INTERVAL_SEC = 3
LOOKBACK_DAYS = 120
TARGET_BUY_COUNT = 3
BUY_PERCENT = 0.33
MAX_OPEN_DELAY_DAYS = 3  # 시초가 대기 주문 만료 한도 (거래일 기준)


def prepare_indicator_df(symbol: str, lookback: int = LOOKBACK_DAYS):
    """
    주어진 종목(symbol)에 대한 가격 데이터를 조회하고,
    RSI(Momentum)와 MACD(Trend Following) 지표 및 시그널 열을 추가한 데이터프레임을 반환합니다.

    Args:
        symbol (str): 조회할 종목의 심볼코드(예: "005930").
        lookback (int): 조회할 데이터의 기간(일 단위, 최근 N개의 데이터).

    Returns:
        pd.DataFrame or None: 지표 컬럼이 추가된 DataFrame. 데이터가 없으면 None 반환.
    """
    df = get_daily_price_df(symbol)
    if df is None or df.empty:
        return None
    df = df.tail(lookback).copy()
    df['RSI_fast'] = compute_rsi(df['Close'], period=7)
    df['RSI_slow'] = compute_rsi(df['Close'], period=14)
    macd_line, macd_signal = compute_macd(df['Close'], fast=8, slow=17, signal=5)
    df['MACD'] = macd_line
    df['Signal'] = macd_signal
    df['Trade_signal'] = trading_signal(df, 'RSI_fast', 'RSI_slow', 'MACD', 'Signal')
    return df


def parse_price(value):
    """
    임의의 값(문자, 실수, 정수 등)을 정수 가격 형태로 변환합니다.
    예외 발생 시 None을 반환합니다.

    Args:
        value: 변환할 값 (str, float 등).

    Returns:
        int or None: 변환된 가격(정수), 변환 불가시 None.
    """
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return None


def determine_buy_qty(price: int, max_cash: float):
    """
    현재 가격과 주문 가능 금액을 기준으로, 매수 가능한 최대 수량(주식 수)을 계산합니다.

    Args:
        price (int): 매수 희망 가격 (정수).
        max_cash (float): 1회 거래에 사용할 최대 현금(예: total_cash * BUY_PERCENT).

    Returns:
        int: 매수 수량. 현금 부족/가격 미정의/오류시 0 반환.
    """
    if price is None or price <= 0:
        return 0
    try:
        available_cash = get_balance()
    except Exception as balance_error:
        send_message(f"[현금 조회 실패]{balance_error}")
        return 0
    buy_cash = min(max_cash, available_cash)
    return int(buy_cash // price)


def bootstrap_positions():
    """
    현재 보유중인 주식을 기반으로 active_positions 딕셔너리를 초기화합니다.
    각 종목을 현재가 기준 진입(bootstrap) 처리로 간주합니다.

    Returns:
        dict: symbol을 key로 하고, 수량/진입가/진입시간/진입방법 등의 정보를 가진 포지션 딕셔너리.
    """
    positions = {}
    stock_dict, eval0 = get_stock_balance()
    for sym, qty in stock_dict.items():
        now_price = parse_price(get_current_price(sym))
        if now_price is None:
            continue
        positions[sym] = {
            "qty": qty,
            "entry_price": now_price,
            "entry_date": datetime.now(),
            "entry_method": "bootstrap",
        }
    return positions


try:
    entry_mode = ENTRY_METHOD.lower()
    if entry_mode not in ("close", "open"):
        raise ValueError("ENTRY_METHOD must be either 'close' or 'open'.")

    ACCESS_TOKEN = get_access_token()

    symbol_dict = {
        "005930": "삼성전자",
        # "092200": "디아이씨",
        "035720": "카카오",
        "000660": "sk하이닉스",
        "036630": "세종텔레콤",
        "166090": "하나머티리얼즈",
        "020150": "롯데에너지머티리얼즈",
        "001500": "현대차증권",
        "267250": "HD현대",
        "489460": "바이오비쥬",
        "036540": "SFA반도체",
        "131970": "두산테스나",
    }
    symbol_list = list(symbol_dict.keys())

    total_cash = get_balance()
    max_trade_cash = total_cash * BUY_PERCENT   # 0.33

    active_positions = bootstrap_positions()
    pending_open_entries = {}
    last_signal_dates = {}

    send_message(f"=== 자동매매 시작 (entry={entry_mode}) ===")

    while True:
        t_now = datetime.now()
        today_idx = t_now.weekday()
        today_str = t_now.strftime("%Y%m%d")
        today_date = t_now.date()
        entry_window_start = t_now.replace(hour=9, minute=5, second=0, microsecond=0)
        exit_watch = t_now.replace(hour=15, minute=15, second=0, microsecond=0)
        hard_exit = t_now.replace(hour=15, minute=20, second=0, microsecond=0)

        if today_idx >= 5:
            send_message("주말입니다. 자동매매 종료.")
            break

        if t_now >= hard_exit:
            for sym in list(active_positions.keys()):
                qty = active_positions[sym]['qty']
                if sell(sym, qty):
                    send_message(f"{symbol_dict.get(sym, sym)} 장마감 강제청산")
                active_positions.pop(sym, None)
            pending_open_entries.clear()
            send_message("장마감, 프로그램 종료")
            break

        # RSI + MACD 진입 감시 (신호 발생일 종가 기준)
        if entry_window_start <= t_now <= exit_watch and len(active_positions) < TARGET_BUY_COUNT:
            for sym in symbol_list:
                if sym in active_positions or len(active_positions) >= TARGET_BUY_COUNT:
                    continue
                try:
                    indicator_df = prepare_indicator_df(sym)
                except Exception as indicator_error:
                    send_message(f"{symbol_dict.get(sym, sym)} 지표 계산 실패: {indicator_error}")
                    continue
                if indicator_df is None or indicator_df.empty:
                    continue
                latest_signal = indicator_df['Trade_signal'].iloc[-1]
                if pd.isna(latest_signal):
                    continue
                signal_date = str(indicator_df['Date'].iloc[-1])
                if latest_signal != 'Buy' or signal_date != today_str:
                    continue
                if last_signal_dates.get(sym) == signal_date:
                    continue
                last_signal_dates[sym] = signal_date

                if entry_mode == "open":
                    pending_open_entries[sym] = {"signal_date": signal_date}
                    send_message(f"{symbol_dict.get(sym, sym)} 매수 신호 발생 - 다음날 시초가 진입 대기")
                    continue

                exec_price = parse_price(get_current_price(sym))
                if exec_price is None:
                    continue
                qty = determine_buy_qty(exec_price, max_trade_cash)
                if qty <= 0:
                    continue
                if buy(sym, qty):
                    active_positions[sym] = {
                        "qty": qty,
                        "entry_price": exec_price,
                        "entry_date": datetime.now(),
                        "entry_method": entry_mode,
                    }
                    send_message(f"{symbol_dict.get(sym, sym)} RSI+MACD 종가 진입({exec_price}원, {qty}주)")
                    print_stock_balance(stock_dict, eval0)

        # 다음날 시초가 진입 처리
        if entry_mode == "open" and entry_window_start <= t_now <= exit_watch:
            for sym, info in list(pending_open_entries.items()):
                if sym in active_positions:
                    pending_open_entries.pop(sym, None)
                    continue
                try:
                    signal_dt = datetime.strptime(info['signal_date'], "%Y%m%d").date()
                except (TypeError, ValueError):
                    pending_open_entries.pop(sym, None)
                    continue
                delay_days = (today_date - signal_dt).days
                if delay_days <= 0:
                    continue
                if delay_days > MAX_OPEN_DELAY_DAYS:
                    pending_open_entries.pop(sym, None)
                    continue
                if len(active_positions) >= TARGET_BUY_COUNT:
                    continue
                exec_price = parse_price(get_current_price(sym))
                if exec_price is None:
                    continue
                qty = determine_buy_qty(exec_price, max_trade_cash)
                if qty <= 0:
                    continue
                if buy(sym, qty):
                    active_positions[sym] = {
                        "qty": qty,
                        "entry_price": exec_price,
                        "entry_date": datetime.now(),
                        "entry_method": "open",
                    }
                    pending_open_entries.pop(sym, None)
                    send_message(f"{symbol_dict.get(sym, sym)} 시초가 진입 완료({exec_price}원, {qty}주)")
                    print_stock_balance(stock_dict, eval0)

        # 익절/손절 감시
        for sym in list(active_positions.keys()):
            now_price = parse_price(get_current_price(sym))
            if now_price is None:
                continue
            entry_price = active_positions[sym]['entry_price']
            if entry_price <= 0:
                continue
            change = (now_price - entry_price) / entry_price
            qty = active_positions[sym]['qty']
            if change >= TAKE_PROFIT_RATE:
                if sell(sym, qty):
                    send_message(
                        f"{symbol_dict.get(sym, sym)} +{TAKE_PROFIT_RATE*100:.1f}% 익절 ({entry_price}→{now_price})"
                    )
                    active_positions.pop(sym, None)
            elif change <= STOP_LOSS_RATE:
                if sell(sym, qty):
                    send_message(
                        f"{symbol_dict.get(sym, sym)} {STOP_LOSS_RATE*100:.1f}% 손절 ({entry_price}→{now_price})"
                    )
                    active_positions.pop(sym, None)

        time.sleep(CHECK_INTERVAL_SEC)

except Exception as e:
    send_message(f"[오류 발생]{e}")
    import traceback, sys
    exc_type, exc_value, exc_traceback = sys.exc_info()
    traceback.print_exception(exc_type, exc_value, exc_traceback)
    time.sleep(1)

{'content': '[2025-12-03 09:13:45] saved token loading'}
{'content': '[2025-12-03 09:13:45] 주문 가능 현금 잔고: 47,961원'}
{'content': '[2025-12-03 09:13:46] === 자동매매 시작 (entry=close) ==='}

KeyboardInterrupt:

In [23]:
tmp_dict = {
    "123": "a",
    "124": "b",
    "125": "c",
    "126": "d",
}

tmp_list = list(tmp_dict.keys())
print(tmp_list)

['123', '124', '125', '126']